### ISSUE TITLE
Pairing information causing errors?

### ISSUE THREAD

**Issue by peterdfields** [bwa-mem2/bwa-mem2#1]
I just gave bwa-mem2 (binaries; building from source doesn't change the effect) a quick try, using paired reads in two separate files, and I got the following error: 

```
[0000] 1: Calling process()

Threads used (compute): 1
Projected #read in a task: 79375
------------------------------------------
Memory pre-allocation for chaining: 2544445000
Memory pre-allocation for BSW: 239617024
Memory pre-allocation for BWT: 51611776
------------------------------------------
No. of pipeline threads: 2
bwa-mem2: src/fastmap.cpp:253: ktp_data_t *kt_pipeline(void *, int, void *, mem_opt_t *, worker_t &): Assertion `ret->n_seqs <= nreads' failed.
Aborted (core dumped)
```
If I run the same command with only the left or right set of reads there isn't an issue. I think an important point here is the way the headers of the fastq encode the left and right read. The read set that I'm working that causes this error arises from mapping followed by subsetting of the bam to retain only mapped reads, and then output with samtools fastq with the -N flag (so left and right are distinguished by the /1 and /2 suffix). If I use the original reads that retain the `@<instrument>:<run number>:<flowcell ID>:<lane>:<tile>:<x-pos>:<y-pos> <read>:<is filtered>:<control number>:<sample number> ` format then bwa-mem2 seems to work fine. Note that both read sets work with bwa-mem so I assume the error is just arising as a result of the pairing information? Please let me know if additional information would be useful.

**Comment by lh3** [comment]
Do you have example input?

**Comment by peterdfields** [comment]
Sure, I can share the read set with you. Is there an email address I could send the link to?

**Comment by lh3** [comment]
Do you see the error in a small set of reads? Thanks.

**Comment by lh3** [comment]
I understand what happens to this. I don't need sample data any more.

**Comment by NickyPan** [comment]
yeah, I got the error either, waiting for good news

**Comment by peterdfields** [comment]
This error seems fixed now if building from source at commit ` dc3bb8d`, though probably before. I will close this issue now.
