### ISSUE TITLE
Running into errors while compiling from source

### ISSUE THREAD

**Issue by IAnalyzeGenomes** [bwa-mem2/bwa-mem2#102]
It looks like the latest improvements in memory footprint and indexing are not available via downloading bwa-mem2 using conda or by using pre-compiled binaries. So, I am trying to compile bwa-mem2 from source following the instructions in 'Getting Started" section of README. However, below is the error I get.. 

**g++: error: unrecognized command line option ‘-mavx512bw’**
**make[1]: *** [src/fastmap.o] Error 1**

Would appreciate your help in resolving this.

**Comment by keiranmraine** [comment]
Have you checked the version of gcc you are using understands the avx512bw option?

Seems to be fine with:

```
$ which gcc
$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by IAnalyzeGenomes** [comment]
Thanks Keiran. Appreciate your help.

I have now updated gcc to 7.5.0. I then ran into below error.

```
g++ -c -g -O3 -fpermissive -mavx512bw  -DENABLE_PREFETCH -DV17=1 -DSAIS=1  -Isrc -Iext/safestringlib/include src/ksw.cpp -o src/ksw.o
/tmp/ccrpiJ5B.s: Assembler messages:
/tmp/ccrpiJ5B.s:2625: Error: no such instruction: `vmovdqu8 (%rdi,%rcx),%zmm0'
/tmp/ccrpiJ5B.s:2629: Error: no such instruction: `vpermi2w %zmm0,%zmm0,%zmm6'
.
.
.
/tmp/ccrpiJ5B.s:5943: Error: operand type mismatch for `vpmovsxbw'
/tmp/ccrpiJ5B.s:5947: Error: operand type mismatch for `vpmovsxbw'
make[1]: *** [src/ksw.o] Error 1
make[1]: Leaving directory `/media/Win64_Ubuntu64_Shared/BWA-GATK/bwa-mem2'
make: *** [multi] Error 2
```
I guess it was due to gcc incompatibility with GNU Binutils.  I was using below version. 
```
$ld -v
GNU ld (GNU Binutils for Ubuntu) 2.24
```
I then updated it to 2.26 (below post was helpful) which resolved this issue! 
https://stackoverflow.com/questions/52754728/how-to-convert-default-binutils-into-binutils-2-26

Now looking forward to indexing and mapping!
