### ISSUE TITLE
release assets 

### ISSUE THREAD

**Issue by keiranmraine** [bwa-mem2/bwa-mem2#104]
Hi,

Can you clarify if the pre-compiled binaries are icpc or gcc?

Also can the `Source_code_including_submodule.tar.gz` asset be reinstated?

Thanks

**Comment by sanchit-misra** [comment]
Hi @keiranmraine,

The precompiled binaries were compiled using icpc 2018. I have added Source_code_including_submodules.{zip/tar.gz}.
