### ISSUE TITLE
BWA-MEM2 2.1 not producing same results as BWA-MEM 0.7.17

### ISSUE THREAD

**Issue by moldach** [bwa-mem2/bwa-mem2#105]
I'm trying to reproduce a pipeline previously written in our lab and there seems to be a discrepancy in the output which I've traced back to a `bwa-mem`/`bwa-mem2` difference (I think I've ruled out `samtools` version differences)

I'm using a [docker container](https://hub.docker.com/r/dceoy/bwa-mem2/dockerfile) which is pulling the latest version of `bwa-mem2` and `samtools v1.5` I created to match the _legacy_ pipeline.

## `Snakemake` rule(s)

```
elif (config["ALIGN_TOOL"]=="bwa-mem2"):
        rule bwa_mem2:
                input:
                        reads=lambda wildcards: getTrims(wildcards.sample),
                        aaa=os.path.join(dirs_dict["REF_DIR"],AAA),
                        amb=os.path.join(dirs_dict["REF_DIR"],AMB),
                        ann=os.path.join(dirs_dict["REF_DIR"],ANN),
                        bwt2=os.path.join(dirs_dict["REF_DIR"],BWT2),
                        bwt8=os.path.join(dirs_dict["REF_DIR"],BWT8),
                        pac=os.path.join(dirs_dict["REF_DIR"],PAC)
                output:
                        os.path.join(dirs_dict["ALIGN_DIR"],config["ALIGN_TOOL"],"{sample}.sam")
                log: os.path.join(dirs_dict["LOG_DIR"],config["ALIGN_TOOL"],"{sample}.log")
                threads: 8
                resources:
                        mem=4000,
                        time=100
                params:
                        index=os.path.join(dirs_dict["REF_DIR"],config["REF_GENOME"]),
                        sample="{sample}",
                        threads=8,
                container:
                        "docker://dceoy/bwa-mem2:latest"
                shell: """
                /usr/local/bin/bwa-mem2 mem \
                -t {params.threads} \
                -R '@RG\tID:{params.sample}\tPL:ILLUMINA\tSM:{params.sample}' \
                {params.index} \
                {input.reads} > {output}
                """
align_dir=os.path.join(dirs_dict["ALIGN_DIR"],config["ALIGN_TOOL"])
        aligns_locations=[align_dir] * len_samples
        aligns_dict=dict(zip(sample_names, aligns_locations))
        def getSams(sample):
          return(list(os.path.join(aligns_dict[sample],"{0}.sam".format(sample,pair)) for pair in ['']))
        rule sam_2_bam:
                input: lambda wildcards: getSams(wildcards.sample)
                output: os.path.join(dirs_dict["ALIGN_DIR"],config["ALIGN_TOOL"],"{sample}.bam")
                log: os.path.join(dirs_dict["LOG_DIR"],config["ALIGN_TOOL"],"{sample}_sam_2_bam.log")
                resources:
                        mem=5000,
                        time=60
                container:
                        "docker://moldach686/samtools-v1.5:0.0.2"
                shell: """
                samtools view -Sbh {input} > {output}
                """

```

## Original pipeline

```
# create SAM
module load bwa/0.7.17
bwa mem -t 4 \
        -R '@RG\tID:sample\tPL:ILLUMINA\tSM:sample' \
        c_elegans.PRJNA13758.WS265.genomic.fa \
        sample_R1_trim_paired.fq.gz \
        sample_R2_trim_paired.fq.gz > sample.sam;


module load nixpkgs/16.09
module load gcc/5.4.0
module load samtools/1.5

# convert SAM->BAM
samtools view -Sbh sample.sam > sample.bam
```

## differences

```
$ diff -q snakemake/sample.bam original/sample.bam
Files snakemake/sample.bam and original/sample.bam differ
```

**Comment by keiranmraine** [comment]
The headers will be different, if nothing else to say that the program was bwa-mem2.

A simple way to reliably compare would be:

```
comm -23 <(samtools view snakemake/sample.bam) <(samtools view original/sample.bam) | wc -l
```

The above will only compare the "records" not the headers and give a count of items unique to the left "file".

I'd also recommend running the following so you can see how the headers differ:

```
diff <(samtools view -H snakemake/sample.bam) <(samtools view -H original/sample.bam) | wc -l
```

Additionally updating your htslib/samtools (now on 1.11) will have a large impact on compression/decompression (especially if you use libdeflate when compiling htslib).

**Comment by moldach** [comment]
Apologies for the delay. This is what I see for the headers:

```
$ diff <(samtools view -H snakemake/sample.bam) <(samtools view -H original/sample.bam) | wc -l
4
```

And the "records" show that there are indeed items unique to the left file?

Shouldn't these be identical?

> "Bwa-mem2 is the next version of the bwa-mem algorithm in bwa. It produces alignment identical to bwa ... "

**Comment by keiranmraine** [comment]
1. Which version of bwa-mem2 are you using?
2. Did you regenerate the index files if you have moved to 2.1 since generation.

**Comment by yuk12** [comment]
"$ diff <(samtools view -H snakemake/sample.bam) <(samtools view -H original/sample.bam) | wc -l
4"

The two files do differ in two lines due to the header line, hence "4" is the result of the wc.

**Comment by moldach** [comment]
> 
> 
> "$ diff <(samtools view -H snakemake/sample.bam) <(samtools view -H original/sample.bam) | wc -l
> 4"
> 
> The two files do differ in two lines due to the header line, hence "4" is the result of the wc.

Thanks @yuk12

**Comment by cbrueffer** [comment]
The version wasn't bumped before 2.1 release, so 2.1 reports itself as 2.0.

FYI, I'm also seeing differences between bwa 0.7.17 and bwa-mem 2.1 (Bioconda version, haven't checked 2.0), with indexes rebuilt by bwa-mem 2.1. I'll add details once I've re-run and confirmed everything.

**Comment by keiranmraine** [comment]
@moldach I ran 4 22Mbase datasets through bwa-0.7.17 and the same ones through bwa-mem2-2.1 on 3 different chipsets.  All gave identical results.  I am preparing to run on far larger datasets now.

**Comment by keiranmraine** [comment]
You could try the binaries in this container, compiled with plain-old gcc:

docker pull quay.io/wtsicgp/pcap-core:5.5.0

**Comment by cbrueffer** [comment]
False alarm on my end, sorry. Alignments of 7 WGS samples with bwa 0.7.17 and bwa-mem2 2.1 are identical. Must have been stale intermediate files somewhere.

**Comment by moldach** [comment]
I rebuilt indexes with `bwa-mem 2.1` and the difference persists.

```
[moldach@cedar5 bwa]$ comm -23 <(samtools view MTG470_trim_bwaMEM.sam) <(samtools view ../../../COOVAR/alignment/bwa-mem2/MTG470.sam) | wc -l
comm: file 2 is not in sorted order
comm: file 1 is not in sorted order
336899
```

The way that the sorted `.bam` files are produced is slightly different (though I assume should produce the same output)

## Method 1

### Snakemake rules produce the following shell code:

```
bwa-mem2 mem \
                -t 8 \
                -R '@RG\tID:{params.sample}\tPL:ILLUMINA\tSM:{params.sample}' \
                {params.index} \
                {input.reads} > {output}
samtools view -Sbh snakemake/sample.sam > snakemake/sample.bam
samtools sort -o  snakemake/sample_sorted.bam  snakemake/sample.bam
```

## Method 2


```
# BWA 0.7.17
module load bwa/0.7.17
bwa mem -t 4 \
        -R '@RG\tID:MTG470\tPL:ILLUMINA\tSM:MTG470' \
        /home/moldach/projects/def-mtarailo/common/indexes/WS265_wormbase/c_elegans.PRJNA13758.WS265.genomic.fa \
        original/sample_R1_trim_paired.fq.gz \
        original/sample_R2_trim_paired.fq.gz > original/sample.sam;

# Samtools 1.5
module load nixpkgs/16.09
module load gcc/5.4.0
module load samtools/1.5
samtools sort -o original/sample_sorted.bam original/sample.sam;
```


The difference:

```
$ comm -23 <(samtools view original/sample_sorted.bam) <(samtools view snakemake/sample_sorted.bam) | wc -l
comm: file 2 is not in sorted order
comm: file 1 is not in sorted order
380418
```

**Comment by moldach** [comment]
Is it possible there are different variants of `bwa` version `0.7.17` that could be causing this?

> Version: `0.7.17-r1188`

```
$ module load bwa/0.7.17
$ bwa
(snakemake) [moldach@cedar1 varscan_coovar]$ bwa

Program: bwa (alignment via Burrows-Wheeler transformation)
Version: 0.7.17-r1188
Contact: Heng Li <lh3@sanger.ac.uk>

Usage:   bwa <command> [options]

Command: index         index sequences in the FASTA format
         mem           BWA-MEM algorithm
         fastmap       identify super-maximal exact matches
         pemerge       merge overlapping paired ends (EXPERIMENTAL)
         aln           gapped/ungapped alignment
         samse         generate alignment (single ended)
         sampe         generate alignment (paired ended)
         bwasw         BWA-SW for long queries

         shm           manage indices in shared memory
         fa2pac        convert FASTA to PAC format
         pac2bwt       generate BWT from PAC
         pac2bwtgen    alternative algorithm for generating BWT
         bwtupdate     update .bwt to the new format
         bwt2sa        generate SA from BWT and Occ

Note: To use BWA, you need to first index the genome with `bwa index'.
      There are three alignment algorithms in BWA: `mem', `bwasw', and
      `aln/samse/sampe'. If you are not sure which to use, try `bwa mem'
      first. Please `man ./bwa.1' for the manual.
```

**Comment by keiranmraine** [comment]
If you want to get to the bottom of this only test the binaries.  Both bwa and bwa-mem2 provide pre-built binaries attached to the releases:

* [bwa binary](https://github.com/lh3/bwa/releases/download/v0.7.17/bwa-0.7.17.tar.bz2) archive
* [bwa-mem2 binary](https://github.com/bwa-mem2/bwa-mem2/releases/download/v2.1/bwa-mem2-2.1_x64-linux.tar.bz2) archive

Sorry to say you should delete and rebuild the index just to be really sure, both bwa's can share the new reference.

You only need to run bwa/bwa-mem2 to compare the outputs.  As far as I am aware the output order should be the same as the read inputs without sorting.  I would expect you could probably run something like this with 40-50GB of RAM.

```
bwa mem ... | gzip --fast -c > bwa.sam.gz
bwa-mem2 mem ... | gzip --fast -c > bwa-mem2.sam.gz
comm --nocheck-order -23 <(gunzip -c bwa.sam.gz) <(gunzip -c bwa-mem2.sam.gz) | wc -l
```

I personally don't use the provided bwa-mem2 binary as the intel compiler is detrimental on some of our legacy hardware.  [This document shows this](https://docs.google.com/spreadsheets/d/11RkIE_h5VsZJ3CeOjoyFm-cPysSreLnRv8zv4djnPMI/edit?usp=sharing), but also covers confirmation that results were identical on 4x 22Mbp WGS human samples.

I am currently running ~90 complete WGS high depth samples and comparing results.  The first file which I've been able to compare consisted of 154Gbp from 6 lanes of sequencing duplicate marked and merged.  This has given identical results, however this data uses a common flow where only bwa is changed.

**Comment by yuk12** [comment]
@moldach please run with same number of threads for original as well as bwa-mem2. Your log shows that bwa-mem2 is run with 8 threads and bwa-mem is run with 4 threads.

**Comment by ChrDec** [comment]
Hello,

we have a different output between bwa 0.7.17-r1188 and bwa-mem2 2.1 as well. Genome index was build with the current version of bwa-mem2. Here is an example output between both alignments:

bwa-mem2 alignment:
A00515:218:HN772DRXX:1:2202:6442:9768	385	1	725510	0	24H94M32H	10	39112272	0	*	*	MC:Z:67H77M6H	MD:Z:6A16A2G3T18C1C3A3T14C11G7	RG:Z:13013-17	NM:i:10	AS:i:44

bwa 0.7.17-r1188 alignment:
A00515:218:HN772DRXX:1:2202:6442:9768	65	10	39112272	0	67S77M6S	Y	13811045	0	CATTCCACTCCATTCCATATTAATCCATTACACTCCATTCCATTCTATTACTTTCATTTCCATTCAGTTCCAATCCATTTGATTCCATTCCACTCGGTTTCACTCCATTTGAGTCCATTCCATTCCATTCCATTCNATTCCATTCCATTC	FFFFFFFF:FFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFF:FF:FFFFFFFFFFFFFFFFFFFFF::FF:,FFF:FFFF,FFF,:,FFFF,:FFFFFFFF:FFF:FFFFFFFFF:FFF:,FFFF,FFFFF#FF,FFFFFFFFF:F	SA:Z:10,39149080,-,78S49M23S,0,3;21,10849547,-,131S19M,0,0;	MC:Z:32S78M40S	MD:Z:5T23A2C2A8T12G10C8	RG:Z:13013-17	NM:i:7	AS:i:45	XS:i:45

I am wondering, because bwa-mem2 reports an '*' instead of the read sequence like bwa does. Is this correct?

Here are the original reads from the FASTQ files:
Read from FASTQ file R1:
@A00515:218:HN772DRXX:1:2202:6442:9768 1:N:0:AATGTTCT+AGTCACCT
CATTCCACTCCATTCCATATTAATCCATTACACTCCATTCCATTCTATTACTTTCATTTCCATTCAGTTCCAATCCATTTGATTCCATTCCACTCGGTTTCACTCCATTTGAGTCCATTCCATTCCATTCCATTCNATTCCATTCCATTC
+
FFFFFFFF:FFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFF:FF:FFFFFFFFFFFFFFFFFFFFF::FF:,FFF:FFFF,FFF,:,FFFF,:FFFFFFFF:FFF:FFFFFFFFF:FFF:,FFFF,FFFFF#FF,FFFFFFFFF:F

Read from FASTQ file R2:
@A00515:218:HN772DRXX:1:2202:6442:9768 2:N:0:AATGTTCT+AGTCACCT
GGAAGGGAATGGAGTGGAATCAAGTGGAATCGAATGGAATGGAATGGGATTGAAAGGAATGGAATGGAATAGAATGGAATGGACTGGAATGGAATGGAATCGAATGGAATCGAATGGAACANTATGGAATGGTACCGAATGTAATGGAAT
+
FFFFF:FFFFFFF:FF:FFFFFFFF:,FFFFFFFFFF:FFFFFFFFF,FFF,FFFFFF:FF,:F::FFF:FFFFFFFF,F,FFFFFFFF:FFFFF,FFFFFFFFFFF:FF:FFFFF,FF,F#FFFF,FF:F:FF,FFFFFF,:FFFFFFF

Thank you very much for your help.

Best regards,
Chris

**Comment by moldach** [comment]
> 
> 
> > ```
> > 1. Which version of bwa-mem2 are you using?
> > ```
> 
> I'm using a container I found on Docker Hub which was updated the most recently:
> 
> ```
> container:
>                         "docker://dceoy/bwa-mem2:latest"
> ```
> 
> This is what it's `Dockerfile` looks like:
> 
> ```
> FROM ubuntu:latest
> ENV DEBIAN_FRONTEND noninteractive
> ADD https://raw.githubusercontent.com/dceoy/print-github-tags/master/print-github-tags /usr/local/bin/print-github-tags
> RUN set -e \
>       && ln -sf bash /bin/sh
> RUN set -e \
>       && apt-get -y update \
>       && apt-get -y dist-upgrade \
>       && apt-get -y install --no-install-recommends --no-install-suggests \
>         ca-certificates curl \
>       && apt-get -y autoremove \
>       && apt-get clean \
>       && rm -rf /var/lib/apt/lists/*
> RUN set -eo pipefail \
>       && chmod +x /usr/local/bin/print-github-tags \
>       && print-github-tags --release --latest bwa-mem2/bwa-mem2 \
>         | tr -d v \
>         | xargs -i curl -SL \
>           https://github.com/bwa-mem2/bwa-mem2/releases/download/v{}/bwa-mem2-{}_x64-linux.tar.bz2 \
>           -o /tmp/bwa-mem2.tar.gz \
>       && tar xvf /tmp/bwa-mem2.tar.gz -C /usr/local/src --remove-files \
>       && mv /usr/local/src/bwa-mem2-* /usr/local/src/bwa-mem2 \
>       && cd /usr/local/src/bwa-mem2 \
>       && find /usr/local/src/bwa-mem2 -maxdepth 1 -type f -executable \
>         -exec ln -s {} /usr/local/bin \;
> ENTRYPOINT ["/usr/local/bin/bwa-mem2"]
> ```
> 
> To me this looks like it would be pulling in the most recent release from the official repo. However, I see version `2.0` and not `2.21`???


I can confirm it was this container that was the issue.

**Comment by moldach** [comment]
FYI built the proper one with:

```
FROM quay.io/wtsicgp/pcap-core:5.5.0
ENV DEBIAN_FRONTEND noninteractive
ADD https://raw.githubusercontent.com/dceoy/print-github-tags/master/print-github-tags /usr/local/bin/print-github-tags
RUN set -e \
      && ln -sf bash /bin/sh
RUN set -e \
      && apt-get -y update \
      && apt-get -y dist-upgrade \
      && apt-get -y install --no-install-recommends --no-install-suggests \
        ca-certificates curl \
      && apt-get -y autoremove \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/*
RUN set -eo pipefail \
      && chmod +x /usr/local/bin/print-github-tags \
      && print-github-tags --release --latest bwa-mem2/bwa-mem2 \
        | tr -d v \
        | xargs -i curl -SL \
          https://github.com/bwa-mem2/bwa-mem2/releases/download/v2.1/bwa-mem2-2.1_x64-linux.tar.bz2 \
          -o /tmp/bwa-mem2.tar.gz \
      && tar xvf /tmp/bwa-mem2.tar.gz -C /usr/local/src --remove-files \
      && mv /usr/local/src/bwa-mem2-* /usr/local/src/bwa-mem2 \
      && cd /usr/local/src/bwa-mem2 \
      && find /usr/local/src/bwa-mem2 -maxdepth 1 -type f -executable \
        -exec ln -s {} /usr/local/bin \;
ENTRYPOINT ["/usr/local/bin/bwa-mem2"]
```
