### ISSUE TITLE
BWA-MEM2 Index RAM usage

### ISSUE THREAD

**Issue by ana-stankovic** [bwa-mem2/bwa-mem2#111]
Hello, I have run the bwa-mem2 index (v2.1) on AWS instances for different fasta files, and the RAM usage is particularly high.
For example: for a ~3GB GRCh38_primary_assembly.fasta file, it uses 62GB RAM for the most time, with a peak of 74GB near the end of the run. 
On various files, it uses around 20-25 times input fasta size for RAM, is this memory usage expected?
Thank you

**Comment by yuk12** [comment]
yes, for indexing, it uses ~70GB RAM for the human genome. The size of the created index and the reference though is ~15GB, so during mapping, the memory usage, in general, is expected to be around ~30GB.

**Comment by ana-stankovic** [comment]
Thank you for the confirmation!

**Comment by millerh1** [comment]
I can index hg38 easily with `bwa` on my PC, but I can't even get close with `bwa-mem2` unless I log into my university's cluster.  I guess I might be naive, but is it not possible to reduce the required memory footprint of `bwa-mem2` for indexing? Could intermediates not be written to disk? Or offer some option that can limit the memory? This problem makes it difficult to use `bwa-mem2` for a very large number of common use cases and I would argue this means `bwa-mem2` is largely not a suitable replacement for `bwa`.
