### ISSUE TITLE
BWA MEM 2 in the WDL with Cromwell it returns and error code of 1.

### ISSUE THREAD

**Issue by dishasharma** [bwa-mem2/bwa-mem2#116]
The tail of the stderr log looks pretty clean but Cromwell gets 1  and thinks it is an error.

 

Also BWA Mem 2 program is using 52GB of memory.

 

….

o. of OMP threads: 12

Processor is runnig @2494.053406 MHz

Runtime profile:

 

        Time taken for main_mem function: 1478.63 sec

 

        IO times (sec) :

        Reading IO time (reads) avg: 469.87, (469.87, 469.87)

        Writing IO time (SAM) avg: 615.04, (615.04, 615.04)

        Reading IO time (Reference Genome) avg: 5.79, (5.79, 5.79)

        Index read time avg: 59.44, (59.44, 59.44)

 

        Overall time (sec) (Excluding Index reading time):

        PROCESS() (Total compute time + (read + SAM) IO time) : 1408.69

        MEM_PROCESS_SEQ() (Total compute time (Kernel + SAM)), avg: 1400.67, (1400.67, 1400.67)

 

         SAM Processing time (sec):

        --WORKER_SAM avg: 414.18, (414.18, 414.18)

 

        Kernels' compute time (sec):

        Total kernel (smem+sal+bsw) time avg: 975.30, (975.30, 975.30)

                SMEM compute avg: 367.06, (367.53, 366.22)

                SAL compute avg: 89.40, (89.75, 89.08)

                BSW time, avg: 440.02, (440.34, 439.42)

 

        Total re-allocs: 114175268 out of total requests: 438999301, Rate: 0.26

 

Important parameter settings:

        BATCH_SIZE: 512

        MAX_SEQ_LEN_REF: 256

        MAX_SEQ_LEN_QER: 128

        MAX_SEQ_LEN8: 128

        SEEDS_PER_READ: 500

        SIMD_WIDTH8 X: 64

        SIMD_WIDTH16 X: 32

        AVG_SEEDS_PER_READ: 64

INFO    2020-10-28 11:22:12     AbstractAlignmentMerger Wrote 32243927 alignment records and 317733 unmapped reads.

[Wed Oct 28 11:22:12 PDT 2020] picard.sam.MergeBamAlignment done. Elapsed time: 24.65 minutes.

Runtime.totalMemory()=1603796992

This is the tail of Bwa-mem2 log. I am not able to understand why it is exiting with error code 1. I am piping SamToFastq output to Bwamem2 and the output of Bwamem2 to Picard MergeBam as given in CROMWELL format.

**Comment by rhpvorderman** [comment]
If you are piping the program the exit code will be of the last program (i.e. Picard MergeBAM) unless `set -o pipefail` is set. Which WDL pipeline are you using?

**Comment by yuk12** [comment]
A look into the WDL scripts which dishasharma sent me through email revealed that it was a slight difference between bwamem and bwamem2 stderr log ( read 0 ALT contigs vs Read 0 ALT contigs) that was leading to the failure of a grep command after the mergeBam stage. It was not an issue with bwa-mem2.
