### ISSUE TITLE
segmentation fault building index with commit 97a2db0 

### ISSUE THREAD

**Issue by jelber2** [bwa-mem2/bwa-mem2#12]
Hi,
I get a segmentation fault when building an index with commit https://github.com/bwa-mem2/bwa-mem2/commit/97a2db04070c1efd2b6281a68d8917b82bed97cf, which I don't get with commit https://github.com/bwa-mem2/bwa-mem2/commit/a9fd42d6db8d91216ccacb6dbf68ee5c0fedcbfa

Here's the assembly I was indexing, which now gives me a segmentation fault on commit 97a2db0

    wget https://www.dropbox.com/s/jpozyb4avje01p8/abyss.fa.gz

    gunzip abyss.fa.gz

    ./bwa-mem2 index -p abyss ../../abyss.fa
    [bwa_index] Pack FASTA... Segmentation fault (core dumped)

The CPU architecture is Intel SSE4.1

**Comment by sanchit-misra** [comment]
We will look into it and get back to you.

**Comment by yuk12** [comment]
Please try with the latest commit.

**Comment by jelber2** [comment]
Thanks it is working!
