### ISSUE TITLE
Ref index preload

### ISSUE THREAD

**Issue by slw287r** [bwa-mem2/bwa-mem2#120]
Hi, 

Will the preloading the index into RAM for repeated use feature in bwa be available in bwa-mem2? We found that feature useful on fat node.

Cheers,
Richard

**Comment by yuk12** [comment]
With index size roughly 2x of original bwa-mem, do you still need this solution? The time for loading the index is not that significant.

**Comment by slw287r** [comment]
Agree.

**Comment by slw287r** [comment]
Hi Vasimuddin,

I managed to port the mmap feature brought into bwa by Luca Pireddu ([https://github.com/slw287r/bwa-mem2/tree/mmap](url)) to bwa-mem2 ([https://github.com/slw287r/bwa-mem2/tree/mmap](url)). 

It did lower the ram usage by sharing the index files in cache (16.1G), via the `-z` option:

<img width="504" alt="bwa_mmap" src="https://user-images.githubusercontent.com/4134899/115111547-740e7900-9fb3-11eb-87fa-d1717a530b49.png">

I noticed the shm_index branch which make use of `/dev/shm` ([https://github.com/bwa-mem2/bwa-mem2/tree/shm_index](url)),  I had no idea how to use it after compilation.
```
$ bwa-mem2-shm shm

Usage: bwa shm [-d|-l][idxbase]

Options: -d       destroy all indices in shared memory
         -l       list names of indices in shared memory
```


Anyway, the mmap way is more convenient and worth trying.

Cheers,
Richard

**Comment by ythuang0522** [comment]
@slw287r Hi Richard, we were also looking for the shm version and found your solution. It the usage the same as original one?

**Comment by slw287r** [comment]
> @slw287r Hi Richard, we were also looking for the shm version and found your solution. Is the usage the same as original one?

The usage is the same as the original bwa-mem2, use `-z` to activate reference mmap.

**Comment by ythuang0522** [comment]
> The usage is the same as the original bwa-mem2, use `-z` to activate reference mmap.
@slw287r Thanks Richard. Your code can be successfully compiled on my machine. However,  I confused with the usage of previous bwa shm with your implementation, which requiring running "bwa shm my.fa" prior to subsequent alignments " bwa mem my.fa myreads1.fq" "bwa mem my.fa myreads2.fq" for keeping the index in the memory.  If my understanding is correct, the first "bwa mem -z my.fa myreads1.fq" would load the index in memory and the second "bwa mem -z my.fa myreads2.fq" would directly access the pre-loaded index in RAM, without the need for running "bwa shm". You help is highly appreciated.
