### ISSUE TITLE
BWA-MEM2 ignores write errors generated by disk quotas

### ISSUE THREAD

**Issue by lfearnley** [bwa-mem2/bwa-mem2#121]
Hi BWA-MEM2 team!

BWA-MEM2 (2.0pre2) seems to ignore error codes produced on write attempts - this occurred on a HPC using Lustre with a storage quota. When these write commands fail, it seems to ignore the error and silently attempt to rewrite data or proceed to the next block.

A trace on one of the processes looks like:

`[pid 619660] write(3, "ST-E00180:170:HY7F3CCXX:7:1111:2"..., 8192) = -1 EDQUOT (Disk quota exceeded)
[pid 619660] write(3, "ST-E00180:170:HY7F3CCXX:7:1111:2"..., 8192) = -1 EDQUOT (Disk quota exceeded)
[pid 619660] write(3, "ST-E00180:170:HY7F3CCXX:7:1111:3"..., 8192) = -1 EDQUOT (Disk quota exceeded)
[pid 619660] write(3, "ST-E00180:170:HY7F3CCXX:7:1111:3"..., 8192) = -1 EDQUOT (Disk quota exceeded)
[pid 619660] write(3, "ST-E00180:170:HY7F3CCXX:7:1111:3"..., 8192) = -1 EDQUOT (Disk quota exceeded)
[pid 619660] write(3, "ST-E00180:170:HY7F3CCXX:7:1111:3"..., 8192) = -1 EDQUOT (Disk quota exceeded)
[pid 619660] write(3, "ST-E00180:170:HY7F3CCXX:7:1111:3"..., 8192) = -1 EDQUOT (Disk quota exceeded)
[pid 619660] write(3, "ST-E00180:170:HY7F3CCXX:7:1111:3"..., 8192) = -1 EDQUOT (Disk quota exceeded)`

I was running a number of alignments in parallel, so this caused excess load on the quota managers and caused system wide performance issues on the system we were aligning on.

I think the expected behaviour should be a retry or an exit with a non-zero exit code on write errors of this kind?

**Comment by yuk12** [comment]
Please try with the latest release and check?

**Comment by lfearnley** [comment]
@yuk12 - I'll get back to you on this once I set up a suitable test environment with the HPC server admins.

**Comment by lfearnley** [comment]
Might need to mark this as stale; I've been unable to arrange to get an isolated test environment in which to try to safely reproduce the issue. If I run into it again I'll reopen.
