### ISSUE TITLE
Do you recommend removing adapters using trimadp or other programs before running bwa mem2? 

### ISSUE THREAD

**Issue by diviyasmith** [bwa-mem2/bwa-mem2#124]

**Comment by rhpvorderman** [comment]
I recommend cutadapt. It is very fast. http://journal.embnet.org/index.php/embnetjournal/article/view/200
https://github.com/marcelm/cutadapt

Please use the `-Z` command line flag when using cutadapt. It will be much faster that way.

Trimming adapters is always recommended. These sequences are artifacts and not part of the biological sequence you are interested in. By trimming the adapters you remove noise from your reads that interferes with your analysis.
