### ISSUE TITLE
bwa-mem2 conflicting with picard

### ISSUE THREAD

**Issue by ruslan-abasov** [bwa-mem2/bwa-mem2#129]
bwa command:
bwa-mem2-2.1_x64-linux/bwa-mem2 mem -R "@RG\tID:12\tPL:BGI\tLB:lib\tSM:sample" /home/nikolay/reference/GRCh38/GRCh38.primary_assembly.genome.cleaned.fa -M -Y -K 100000000 /mnt/data/BGI_DATA/F18FTSEUHT1034-08_HUMlfkR_81th_2/Clean/PAB17092020-170096/concat_1.fq.gz /mnt/data/BGI_DATA/F18FTSEUHT1034-08_HUMlfkR_81th_2/Clean/PAB17092020-170096/concat_2.fq.gz -t 8 | /home/nikolay/samtools-1.11/samtools view -bT /home/nikolay/reference/GRCh38/GRCh38.primary_assembly.genome.cleaned.fa -> /mnt/data/BGI_DATA/F18FTSEUHT1034-08_HUMlfkR_81th_2/Clean/PAB17092020-170096/sample.raw.bam

Picard error:
Exception in thread "main" htsjdk.samtools.SAMFormatException: Error parsing SAM header. Problem parsing @PG key:value pair ID:12 clashes with ID:bwa-mem2. Line:
@PG     ID:bwa-mem2     PN:bwa-mem2     VN:2.1  CL:/home/nikolay/bwa-mem2-2.1_x64-linux/bwa-mem2 mem -R @RG     ID:12   PL:BGI  LB:lib       SM:sample /home/nikolay/reference/GRCh38/GRCh38.primary_assembly.genome.cleaned.fa -M -Y -K 100000000 /mnt/data/BGI_DATA/F18FTSEUHT1034-08_HUMlfkR_81th_2/Clean/PAB17092020-170096/concat_1.fq.gz /mnt/data/BGI_DATA/F18FTSEUHT1034-08_HUMlfkR_81th_2/Clean/PAB17092020-170096/concat_2.fq.gz -t 8; File /mnt/data/BGI_DATA/F18FTSEUHT1034-08_HUMlfkR_81th_2/Clean/PAB17092020-170096/sample.sorted.bam; Line number 28

**Comment by ghuls** [comment]
@ruslan-abasov As far as I know, tags in the header should be 2 letters in uppercase, so the read group tag should be written as `@RG`: https://github.com/samtools/hts-specs/blob/master/SAMtags.tex#L259-L263

**Comment by keiranmraine** [comment]
@ruslan-abasov your command has set the `@RG` to lowercase.  I don't believe it's the responsibility of BWA to check that.  

All my runs of bwa-mem2 show `@PG` as upper case.

**Comment by ruslan-abasov** [comment]
Thanks!
