### ISSUE TITLE
There is a bug in the src/fastmap.cpp, the free memory is used in the code

### ISSUE THREAD

**Issue by xuxiali13** [bwa-mem2/bwa-mem2#135]
src/fastmap.cpp 
function:  main_mem
struct 'opt' is freed, but reuse in 'display_stats(aux.opt->n_threads)'

### To illustrate, I added two lines of print to the code , line 958, line 960
![image](https://user-images.githubusercontent.com/26106192/110723498-1b7aec00-824f-11eb-8eb2-d7f12c1b70b2.png)
![image](https://user-images.githubusercontent.com/26106192/110724054-0a7eaa80-8250-11eb-9c9d-12ab13b5be2b.png)

### add option '-fsanitize=address' in g++ and link， can see the error very clearly
![image](https://user-images.githubusercontent.com/26106192/110723664-5b41d380-824f-11eb-9cec-f81684f9187d.png)

**Comment by yuk12** [comment]
Thanks for pointing it out. fixed it.
