### ISSUE TITLE
benchmar against minimap2

### ISSUE THREAD

**Issue by antonkulaga** [bwa-mem2/bwa-mem2#142]
It would also be interesting to see if it is better than minimap2 which give descent performance and quality even on short reads

**Comment by husamia** [comment]
It's not comparing apples to apples. minimap2 is optimized for long reads and bwa-mem2 is optimized for short reads.

**Comment by antonkulaga** [comment]
From my experience minimap2 performed quite well for short reads, I used it instead of bwa in many projects to speed thing up. I believe many other people did same as well. That is why I consider such comparison legitimate

**Comment by lh3** [comment]
Overall, bwa-mem is still preferred over minimap2, as bwa-mem is more robust to sequencing errors and has slightly higher accuracy on simulated data.
