### ISSUE TITLE
Need help with bwa mem2

### ISSUE THREAD

**Issue by fredjarlier** [bwa-mem2/bwa-mem2#15]
Hi 

First I thank you for for the job this is great keep going ;)
I write because I'm blocked with the index creation and the alignment part.

I checkout the source files and make with CXX=icpc multi

Then I start to build a reference form hg19.fa so i did

bwa-mem2 index hg19.fa 

it generates the following files

hg19.amb  
hg19.fa       
hg19.fa.ann          
hg19.fa.fai  
hg19.fasta.map  
hg19.rpac
hg19.ann  
hg19.fa.0123 
 hg19.fa.bwt          
hg19.fa.pac  
hg19.pac        
hg19.rsa
hg19.bwt  
hg19.fa.amb   
hg19.fa.bwt.8bit.32  
hg19.fa.sa  
hg19.rbwt    
hg19.sa

with bwa-mem2.avx2

and finally I start the alignment with

bwa-mem -t 8 $REF $FASTQ1 $FASTQ2 > $SAM

and it used the bwa-mem2.avx2 version 

but when I look the sam file all my reads are aligned in chr1 at position 1 and when I compare with the original bwa this is wrong...I think it's a matter of how the index is created but I'm not sure... Have you an idea when it comes from please?

I also tried the precompiled lib but no help...
I run on Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz

Bests

frederic

**Comment by fredjarlier** [comment]
OK I got it finally I happen to generate the right reference I was a matter of memory.

Work fine now

best

fred

**Comment by sanchit-misra** [comment]
Glad that it worked out. Thanks for updating us.

**Comment by fredjarlier** [comment]
Your welcome. I sure will have further question soon.

f
