### ISSUE TITLE
Replacement for -5 (-#) flag from bwa

### ISSUE THREAD

**Issue by HenryCWong** [bwa-mem2/bwa-mem2#151]
I was wondering if there as a replacement for the -# flag in bwa-mem2? 
When aligning Hi-C data, it is often said to use `bwa mem -SP5M -t<nthreads> <genome_index> <fastq1> <fastq2>`. 

However, the -5 is not recognized by bwa-mem2. I also suspect I am missing something here that is blowing over my still-learning-bio brain because the -5 or -# flag does not appear in the bwa man pages either. 

Thanks!

**Comment by HenryCWong** [comment]
For reference https://data.4dnucleome.org/resources/data-analysis/hi_c-processing-pipeline#alignment uses the "-5" option as: 

The -5 option is used to report the 5' portion of chimeric alignments as the primary alignment. In Hi-C experiments, when a mate has chimeric alignments, typically, the 5' portion is the position of interest, while the 3' portion represents the same fragment as the mate. For chimeric alignments, bwa mem reports two alignments: one of them is annotated as primary and soft-clipped, retaining the full-length of the original sequence. The other end is annotated as hard-clipped and marked as either 'supplementary' or 'secondary'. The -5 option forces the 5'end to be always annotated as primary.

**Comment by yuk12** [comment]
Are you using the latest binaries? "-5" option is supported by bwa-mem2.

**Comment by HenryCWong** [comment]
So I just updated my version of bwa-mem2 to. I was originally running off the version of bwa-mem2 mentioned in the README.md in the title. I am running into another issue, but I will create a new issue for that as the problem could a separate issue. Thanks!
