### ISSUE TITLE
fastmap.cpp error, no idea why or what's causing it

### ISSUE THREAD

**Issue by Jolleboll** [bwa-mem2/bwa-mem2#155]
Hello!

Error message...
bwa-mem2: src/fastmap.cpp:240: ktp_data_t *kt_pipeline(void *, int, void *, mem_opt_t *, worker_t &): Assertion `w.seedBuf != __null' failed.

**Comment by yuk12** [comment]
Please share the details: command line, bwa-mem2 version, memory available, if possible, complete error log. Looks like memory is insufficient.

**Comment by Jolleboll** [comment]
> Please share the details: command line, bwa-mem2 version, memory available, if possible, complete error log. Looks like memory is insufficient.

Hello and BIG thanks for your reply. I was so relieved to see someone answer. Yes I am now looking at the memory usage history and it peaked to the max before this error occurred. I shall try again with more memory, if that too fails I shall give you the full error log etc. :-]
