### ISSUE TITLE
What is the expected speed improvement?

### ISSUE THREAD

**Issue by vladimirkovacevic** [bwa-mem2/bwa-mem2#16]
I wanted to test speed improvements of BWA-MEM2 over BWA-MEM and run the same WGS 30x sample on AWS instance c5.9xlarge (36CPUS, 72GB):

```
bwa mem -R '@RG\tID:1\tLB:FDA_GARVAN\tPL:Illumina-HiSeq-XTen\tSM:NA12878' -t 36 human_g1k_v37_decoy.fasta NA12878-Garvan-Vial1_R1.fastq.gz NA12878-Garvan-Vial1_R2.fastq.gz  > NA12878-Garvan-Vial1_R.sam 

bwa-mem2 mem -R '@RG\tID:1\tLB:FDA_GARVAN\tPL:Illumina-HiSeq-XTen\tSM:NA12878'  -t 36 human_g1k_v37_decoy.fasta NA12878-Garvan-Vial1_R1.fastq.gz NA12878-Garvan-Vial1_R2.fastq.gz > NA12878-Garvan-Vial1_R.sam
```

BWA-MEM finished in 4 hours, 12 minutes and BWA-MEM2 in 3 hours, 40 minutes.
Is that expected?
BWA-MEM2 log is [attached.](https://transfer.sh/ZZGS4/bwamem2.log).

**Comment by fredjarlier** [comment]
Hi, I cannot see your log maybe zip it...

This what I had from running on Xeon E5

BWA-mem2 = 01:50:12
BWA-mem   = 03:04:33

more than 30% gain in AVX2 mode.

It really depends on the processor architecture

best

fred

**Comment by vladimirkovacevic** [comment]
Loh is here: https://transfer.sh/ZZGS4/bwamem2.log

**Comment by yuk12** [comment]
We have added the performance charts on the speedup of bwa-mem2. Please refer to it for expected speed improvements.
