### ISSUE TITLE
`bwa-mem2': free(): invalid next size (normal): 0x00007f4344068230

### ISSUE THREAD

**Issue by yihhwang** [bwa-mem2/bwa-mem2#17]
Setting:

- Binary built using commit 1038fe3
- Ran on AWS c5d.9xlarge with Linux-4.4.0-1092-aws-x86_64 and Ubuntu-16.04-xenial 
- Executing in AVX512 mode

Note:
  - Same error happens when using AWS c5d.18xlarge. Executing in AVX512 mode.
  - Same binary run successfully without error on AWS c3.8xlarge. Executing in SSE4.1 mode.

Command:
```
bwa-mem2 mem -t 36 genome/hs38DH.fa /home/dnanexus/in/reads_fastqgzs/0/150420_HG005_29-40_R1.fastq.gz /home/dnanexus/in/reads2_fastqgzs/0/150420_HG005_29-40_R2.fastq.gz -K 100000000 -Y -R '@RG\tID:150420_HG005_29-40_1\tPL:ILLUMINA\tPU:150420_HG005_29-40_1\tLB:150420_HG005_29-40\tSM:150420_HG005_29-40'
```

Error message:
```
*** Error in `bwa-mem2': free(): invalid next size (normal): 0x00007f4344068230 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f527cb417e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f527cb4a37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f527cb4e53c]
bwa-mem2[0x44a38d]
bwa-mem2[0x42acba]
bwa-mem2[0x40a501]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f527d9566ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f527cbd141d]
```

We were mapping downsampled HG005 WGS FASTQ as input. We realized that there are specific 12 consecutive read pairs triggering the error. When further removing the read pairs from the top or bottom, mapping succeed without any error.

Below are the files we used:
Reference genome (hs38DH.fa as a tar file): https://dl.dnanex.us/F/D/jG73Z8595GxZYXpKJbqGZzJyX15Q3V0YQG96BxJ7/hs38DH.bwa-index.avx512.v2.tar.gz
150420_HG005_29-40_R1.fastq.gz: https://dl.dnanex.us/F/D/J8J0fp049fG3Yzfyxf0KG7k03YJ6J1P1q4vyz27y/150420_HG005_29-40_R1.fastq.gz
150420_HG005_29-40_R2.fastq.gz: https://dl.dnanex.us/F/D/vbPkzZkjyq6JZQf1j2Jgjjb1xV248fvx10jv254K/150420_HG005_29-40_R2.fastq.gz
STDOUT/STDERR of the run:
https://dl.dnanex.us/F/D/8KzbQy2j5zZ10V6bvK3bjf2Pg9Gqf1bg5qbzbbX7/150420_HG005_29-40.log

**Comment by yihhwang** [comment]
Same error when mapping to hs37d5.fa:

```
*** Error in `bwa-mem2': free(): invalid next size (normal): 0x00007f6b2c060c60 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f7a17bb87e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f7a17bc137a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f7a17bc553c]
bwa-mem2[0x44a38d]
bwa-mem2[0x42acba]
bwa-mem2[0x40a501]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f7a189cd6ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f7a17c4841d]
```

Setting (same as in the original comment):

- Binary built using commit 1038fe3
- Ran on AWS c5d.9xlarge with Linux-4.4.0-1092-aws-x86_64 and Ubuntu-16.04-xenial
- Executing in AVX512 mode

Command:
```
bwa-mem2 mem -t 36 genome/hs37d5.fa /home/dnanexus/in/reads_fastqgzs/0/SRR2962669_1.fastq.gz /home/dnanexus/in/reads2_fastqgzs/0/SRR2962669_2.fastq.gz -K 100000000 -Y -R '@RG\tID:SRR2962669_1\tPL:ILLUMINA\tPU:SRR2962669_1\tLB:SRR2962669\tSM:SRR2962669'
```

Same FASTQ files used as in the original comment.
Reference genome (hs37d5.fa as a tar file):
https://dl.dnanex.us/F/D/2x6Jz6qq69JZkxyj51bFPJxPjY5Y18zYfB6X0z2j/hs37d5.bwa-index.avx512.v2.tar.gz
STDOUT/STDERR of the run:
https://dl.dnanex.us/F/D/QVX7vJ76vx4FK4GBY7Zjb5zzxPQg2f9yxY92PKyb/150420_HG005_29-40_hs37d5.log

**Comment by yuk12** [comment]
Let us look into this and get back.

**Comment by yuk12** [comment]
There was a bug. Thanks for reporting. Please try it out.

**Comment by yihhwang** [comment]
Thanks for the update @yuk12 and @sanchit-misra ! 
Here is the latest test using binary built with commit de3cc78:

The same input using hs38DH failed first, but all 4 other reruns succeeded (1 failure and 4 success). 
A re-run on hs37d5 also succeeded on the first re-run with the new binary. 

The one failed run came with with the following error message. I wonder if this is a random error?
```
bwa-mem2: src/kswv.cpp:759: int kswv::kswv512_u8(unsigned char *, unsigned char *, short, short, dnaSeqPair *, kswr_t *, int, unsigned short, int, int): Assertion `ind == po_ind + i' failed.
```


Full log:
```
-----------------------------
Executing in AVX512 mode!!
-----------------------------
Ref file: genome/hs38DH.fa
Entering FMI_search
reference seq len = 6434693835
count
0,	1
1,	1882204624
2,	3217346918
3,	4552489212
4,	6434693835
Reading other elements of the index from files genome/hs38DH.fa
prefix: genome/hs38DH.fa
[M::bwa_idx_load_ele] read 3171 ALT contigs
Done reading Index!!
Reading reference genome..
Binary seq file = genome/hs38DH.fa.0123
Reference genome size: 6434693834 bp
Done readng reference genome !!
[0000] 1: Calling process()
Threads used (compute): 36
Info: projected #read in a task: 662261
------------------------------------------
Memory pre-allocation for chaining: 1393.3971 MB
Memory pre-allocation for BSW: 8626.2129 MB
Memory pre-allocation for BWT: 2783.3103 MB
------------------------------------------
No. of pipeline threads: 2
[0000] read_chunk: 100000000, work_chunk_size: 19914, nseq: 80
	[0000][ M::kt_pipeline] read 80 sequences (19914 bp)...
[0000] 2. Calling mem_process_seqs.., task: 0
[0000] 3. Calling kt_for - worker_bwt
[0000] read_chunk: 100000000, work_chunk_size: 0, nseq: 0
[0000] 3. Calling kt_for - worker_aln
Inferring insert size distribution from data, l_pac: 3217346917, n: 80
[0000] 10. Calling kt_for - worker_sam
bwa-mem2: src/kswv.cpp:759: int kswv::kswv512_u8(unsigned char *, unsigned char *, short, short, dnaSeqPair *, kswr_t *, int, unsigned short, int, int): Assertion `ind == po_ind + i' failed.
```

**Comment by yuk12** [comment]
Thanks. Let me look into it.

**Comment by yuk12** [comment]
Moved the discussion to issue #35.
