### ISSUE TITLE
Output read ordering

### ISSUE THREAD

**Issue by mikpom** [bwa-mem2/bwa-mem2#177]
Greetings! 

I was wondering if in the output a read is never interrupted by another one ? 

More specifically, is it possible that in the output there will be a snippet like this

> readN (lets say its the first)
> readM (first or second, doesn't matter)
> readN (mate)

?
If this situation is guaranteed to never happen then it can save some substantial computations in the pipeline below.

Many thanks,
Mikhail

**Comment by fredjarlier** [comment]
in bwamem read+mate+alt are always contiguous in output. I think it's the same for bwamem2...why?

**Comment by mikpom** [comment]
Thanks for your reply. 

Some algorithms depend on read name sorted BAM output. Contiguous output is sufficient (alphanumeric sort of read names is not needed) so relying on this eliminates the need of sorting by read name.

If that's for sure I think issue is closed.

**Comment by fredjarlier** [comment]
You're welcome. 
You mean fixing mate? In some cases query sorting could also garanty reproducibility and stable sorting...
But I'm pretty sure queries are contiguous I never saw otherwise.

**Comment by mikpom** [comment]
It is actually for collecting some stats efficiently. 
Unfortunately can't provide more details, since some code I haven't authored is involved. 

Thanks again,
-Mikhail
