### ISSUE TITLE
ERROR! Unable to open the file: 2.bwt.8bit.32

### ISSUE THREAD

**Issue by aderzelle** [bwa-mem2/bwa-mem2#18]
Hello,

I am encountering this issue 
```
./bwa-mem2-2.0pre1_x64-linux/bwa-mem2 index coli.fa
./bwa-mem2-2.0pre1_x64-linux/bwa-mem2 mem 2 -p -t 8 coli.fa paired.fq                                     
-----------------------------
Executing in AVX2 mode!!
-----------------------------
Ref file: 2
Entering FMI_search
ERROR! Unable to open the file: 2.bwt.8bit.32

```
The 2.bwt.8bit.32 file is there and not empty.
```
ls coli.fa*
coli.fa  coli.fa.0123  coli.fa.amb  coli.fa.ann  coli.fa.bwt.2bit.64  coli.fa.bwt.8bit.32  coli.fa.pac
```
I am running Ubuntu 18.04 and my processor is
Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz
thank you

**Comment by luisacusick** [comment]
Did you ever figure out the solution to this? I am having a similar problem. Thank you!

**Comment by sanchit-misra** [comment]
There is an unnecessary "2" in the command after "bwa-mem2 mem", so the tool things that the name of the reference sequence file is "2" and looks for the corresponding index.
