### ISSUE TITLE
Support the input from the pipe

### ISSUE THREAD

**Issue by yewero** [bwa-mem2/bwa-mem2#181]
The `bwa-meth` needs to run `bwa-mem2` with the input from the pipe:
https://github.com/brentp/bwa-meth/blob/94e2b9beb03f88878172cdccb50b8f483a824035/bwameth.py#L366

For example, it runs:
`cat test.fq | bwa-mem2 mem -T 40 -B 2 -L 10 -CM -U 100 -p -R '@RG\tID:t_R\tSM:t_R' -t 12 ref.fa.bwameth.c2t -`
instead of the direct input file name:
`bwa-mem2 mem -T 40 -B 2 -L 10 -CM -U 100 -p -R '@RG\tID:t_R\tSM:t_R' -t 12 ref.fa.bwameth.c2t test.fq`

However, an error will occur in the first strategy:
> [E::main_mem] fail to open file `-'

(The second strategy works well.) 

How could I solve this error in the first strategy?

**Comment by slw287r** [comment]
To read after pipe, replace `-` with `/dev/stdin`:
```
cat test.fq | bwa-mem2 mem -T 40 -B 2 -L 10 -CM -U 100 -p -R '@RG\tID:t_R\tSM:t_R' -t 12 ref.fa.bwameth.c2t /dev/stdin
```

**Comment by yewero** [comment]
@slw287r It works well, thanks.
