### ISSUE TITLE
Using bwa-mem2 as a benchmark tool 

### ISSUE THREAD

**Issue by chenyuetian** [bwa-mem2/bwa-mem2#189]
Hello team,

I am picking up some bioinformatic tools for the benchmark work on the supercomputer cluster I manage, and I think bwa-mem2 is a good candidate. 

Following the steps you listed, I complied the code, downloaded the data and used this command to run bwa-mem2 with 36 threads: 

`./bwa-mem2 mem -t 36 human_g1k_v37.fasta SRR7733443_1.fastq SRR7733443_2.fastq > d3_align.sam`

Now I want to compare the performance results with yours. Could you please let me know which chart or number I should compare with in your "Performance" section? Single End reads 1 thread, Single End reads 56 threads, Paired End reads 1 thread, Paired End reads 56 threads? 

And which number I should use to compare from the bwa-mem2 output? 
`No. of OMP threads: 36
Processor is running @2594.400624 MHz
Runtime profile:

        Time taken for main_mem function: 4965.08 sec

        IO times (sec) :
        Reading IO time (reads) avg: 1540.36, (1540.36, 1540.36)
        Writing IO time (SAM) avg: 1983.44, (1983.44, 1983.44)
        Reading IO time (Reference Genome) avg: 2.50, (2.50, 2.50)
        Index read time avg: 4.45, (4.45, 4.45)

        Overall time (sec) (Excluding Index reading time):
        PROCESS() (Total compute time + (read + SAM) IO time) : 4958.07
        MEM_PROCESS_SEQ() (Total compute time (Kernel + SAM)), avg: 4849.92, (4849.92, 4849.92)

         SAM Processing time (sec):
        --WORKER_SAM avg: 1537.63, (1537.63, 1537.63)

        Kernels' compute time (sec):
        Total kernel (smem+sal+bsw) time avg: 3195.33, (3195.33, 3195.33)
                SMEM compute avg: 928.53, (941.59, 910.79)
                SAL compute avg: 422.56, (427.78, 416.73)
                                MEM_SA avg: 192.58, (195.10, 189.96)

                BSW time, avg: 1511.76, (1514.63, 1506.29)`

`Important parameter settings:
        BATCH_SIZE: 512
        MAX_SEQ_LEN_REF: 256
        MAX_SEQ_LEN_QER: 128
        MAX_SEQ_LEN8: 128
        SEEDS_PER_READ: 500
        SIMD_WIDTH8 X: 64
        SIMD_WIDTH16 X: 32
        AVG_SEEDS_PER_READ: 64`

The whole output is attached: 
[bwa.txt](https://github.com/bwa-mem2/bwa-mem2/files/8225992/bwa.txt)

Thank you so much!

Best,
Yuwu Chen

**Comment by yuk12** [comment]
You can use this time (e2e) for any comparison: " Time taken for main_mem function: 4965.08 sec"
Comparison of your numbers with ours might not be a good idea as the processors might be different in these cases. What you can do is compare the speed up over bwa-mem in your runs. With PE reads bwa-mem2 is ~1.8x - 2x faster than bwa-mem.

**Comment by yuk12** [comment]
It is paired ends reads, because you specify -- SRR7733443_1.fastq SRR7733443_2.fastq.
