### ISSUE TITLE
Non-zero exit code when building genome index

### ISSUE THREAD

**Issue by godotgildor** [bwa-mem2/bwa-mem2#2]
I'm trying out the pre-compiled bwa-mem2 binaries on an AWS r5d.12xlarge (384 GB of RAM, 900 GB storage, 48 cores) and keep exiting with a non-zero exit code while it is writing out the .2bit.64 file.  No error message is presented, so I'm not sure exactly what the underlying problem is.  It is reproducible and deterministic though.  Running on the same reference genome two times in row will result in the same failure with the output files in the exact same state, as determined by running md5sum on all of the output files upon the program exiting:

```
> md5sum hs37d5.fa.*
4a509f50e9ca3027fdb211af51e02bd2  hs37d5.fa.0123
c5287824ea836aed6e34dd2400f83643  hs37d5.fa.amb
b9445ac9206ed3710dce7c6bffcf54a6  hs37d5.fa.ann
c2bb6afb52e2efff51288d33f2b5bcd2  hs37d5.fa.bwt.2bit.64
191da2e42cf9d6f9b7553a9d3cbbdbef  hs37d5.fa.bwt.8bit.32
cbc647939a64ce1e5600f17e499db4f1  hs37d5.fa.pac
```

My command is simply
```
./bwa-mem2 index hs37d5.fa
```

Do you have any suggestions on what I might try?

**Comment by godotgildor** [comment]
In case it is helpful, here are the file sizes:
```
ls -alt hs37d5.fa*
-rw-rw-r-- 1 ubuntu ubuntu 37649454159 May 21 22:58 hs37d5.fa.bwt.2bit.64
-rw-rw-r-- 1 ubuntu ubuntu 43924363151 May 21 22:54 hs37d5.fa.bwt.8bit.32
-rw-rw-r-- 1 ubuntu ubuntu  6274909010 May 21 22:19 hs37d5.fa.0123
-rw-rw-r-- 1 ubuntu ubuntu      106669 May 21 22:16 hs37d5.fa.amb
-rw-rw-r-- 1 ubuntu ubuntu        3276 May 21 22:16 hs37d5.fa.ann
-rw-rw-r-- 1 ubuntu ubuntu   784363628 May 21 22:16 hs37d5.fa.pac
-rw-rw-r-- 1 ubuntu ubuntu  3168829906 May 31  2013 hs37d5.fa
```

**Comment by lh3** [comment]
The index is correct. The bwa-mem2 return code is wrong. Thanks for reporting.
