### ISSUE TITLE
Use system variable as content for Read Group

### ISSUE THREAD

**Issue by kvn95ss** [bwa-mem2/bwa-mem2#200]
As title says, I want to use a system variable as part of Read Group tag (RG). This feature is provided by bwa-mem2 and is quite handy since GATK requires RG for most of their processes.

The syntax I'm using is as follows - 

```bwa-mem2 mem -M -R '@RG\tID:1\tLB:lib1\tPL:ILLUMINA\tSM:$outname\tPU:unit1' -t 40 "$ref_hg38" "$R1" "$R2"```

and also 

```bwa-mem2 mem -M -R '@RG\tID:1\tLB:lib1\tPL:ILLUMINA\tSM:"$outname"\tPU:unit1' -t 40 "$ref_hg38" "$R1" "$R2"```

But the RG in file is literal $outname - 

```@RG     ID:1    LB:lib1 PL:ILLUMINA     SM:$outname   PU:unit1```
```@RG     ID:1    LB:lib1 PL:ILLUMINA     SM:"$outname"   PU:unit1```

How do I ensure the content of variable is included in the RG tag?

**Comment by vasimuddin** [comment]
You are not doing it correctly.
Try this: bwa-mem2 mem -M -R '@RG\tID:1\tLB:lib1\tPL:ILLUMINA\tSM:'$outname'\tPU:unit1' -t 40 "$ref_hg38" "$R1" "$R2"

**Comment by kvn95ss** [comment]
> Try this: bwa-mem2 mem -M -R '@rg\tID:1\tLB:lib1\tPL:ILLUMINA\tSM:'$outname'\tPU:unit1' -t 40 "$ref_hg38" "$R1" "$R2"

It worked like a charm! Looks like I was just quoting things wrongly.
