### ISSUE TITLE
Is there some way to pipe *_1.fastq.gz and *_2.fastq.gz through bwa-mem2 ?

### ISSUE THREAD

**Issue by bgold04** [bwa-mem2/bwa-mem2#201]
Hi!

Since my other programs use compressed fastq files, is there some way to do this with bwa-mem2?

**Comment by hyphaltip** [comment]
current version works with gzipped files natively.
```
bwa-mem2 mem -t CPU GENOME FILE1.gz FILE2.gz > RESULT.SAM
```
If you have bzipped files can try:
```
bwa-mem2 mem -t CPU ref.fa <(bzip2 -dc read1.bz2) <(bzip2 -dc read2.bz2)
```
Via https://sourceforge.net/p/bio-bwa/mailman/bio-bwa-help/thread/512E3D0C.1030807@bcgsc.ca/

**Comment by bgold04** [comment]
Thank you Jason; my files are gzip'd; trying them now.

Best, Bert
