### ISSUE TITLE
Enable alt awareness

### ISSUE THREAD

**Issue by matthdsm** [bwa-mem2/bwa-mem2#208]
Hi,

This might be a stupid question, but when I run `bwa-mem2 mem` I get the following notice after loading the index

```
-----------------------------
Executing in AVX2 mode!!
-----------------------------
* SA compression enabled with xfactor: 8
* Ref file: /references/Hsapiens/hg38/bwamem2/hg38
* Entering FMI_search
* Index file found. Loading index from /references/Hsapiens/hg38/bwamem2/hg38.bwt.2bit.64
* Reference seq len for bi-index = 6434693835
* sentinel-index: 2736215060
* Count:
0,      1
1,      1882204624
2,      3217346918
3,      4552489212
4,      6434693835

* Reading other elements of the index from files /references/Hsapiens/hg38/bwamem2/hg38
* Index prefix: /references/Hsapiens/hg38/bwamem2/hg38
* Read 0 ALT contigs
* Done reading Index!!
* Reading reference genome..
* Binary seq file = /references/Hsapiens/hg38/bwamem2/hg38.0123
```

Notifying me of ZERO alt contigs. How do I make bwa-mem2 detect the alt contigs?

Thanks
M

**Comment by mp15** [comment]
Judging by your naming convention /references/Hsapiens/hg38/bwamem2/hg38.alt needs to exist and contain the alt file.

**Comment by matthdsm** [comment]
I must admit, there's no `alt` file present in the index

**Comment by mp15** [comment]
That is because `alt` isn't a generated index file, it's one you supply and usually get with the .fa file. It is a SAM file which maps the alternate contigs to their locations in the primary reference.

**Comment by matthdsm** [comment]
I must sound ignorant, but that's the first I'm hearing about this.
Is there documentation about this somewhere? Where do I get/ How do I generate this file?

**Comment by matthdsm** [comment]
To confirm:
The `.alt` file was available from our fasta source. Adding it to the index enables `bwa-mem2` to correctly detect the alt contigs.

Thanks fo the tip @mp15 !
