### ISSUE TITLE
`bwa-mem2` treats ALT CONTIGS differently compared to `bwa-mem`

### ISSUE THREAD

**Issue by lydiayliu** [bwa-mem2/bwa-mem2#227]
I have a sample of East Asian descent being aligned with `bwa-mem2` to GRCh38 with Alt Contigs in the reference fasta.

While `bwa-mem` prefers alining reads to the primary chromosome, `bwa-mem2` seems to prefer (at least for some alt contigs) to align to the contigs instead, thus producing non-identical results...

Here's a small example from a section of chromosome 3 that has an alt contig.

`bwa-mem 0.7.17`
```
#CHR    POS     Count_A Count_C Count_G Count_T Good_depth
chr3    184439671       0       0       114     1       115
chr3    184439761       0       0       0       100     100
chr3    184439762       0       0       95      0       95
```

`bwa-mem 2.2.1`
```
#CHR    POS     Count_A Count_C Count_G Count_T Good_depth
chr3    184439671       0       0       18      1       19
chr3    184439761       0       0       0       0       0
chr3    184439762       0       0       0       0       0
```

**Comment by vasimuddin** [comment]
can you provide the command line and point to the data to reproduce the issue at my end?

**Comment by lydiayliu** [comment]
Sorry I forgot to update this. We realized that the issue was on our end, we forgot to include `.alt` as part of the index hence resulting in non-alt-aware mode.

**Comment by vasimuddin** [comment]
ok, great to hear.
