### ISSUE TITLE
Different ouput of bwa-mem2 and bwa/0.7.17 - WHY?

### ISSUE THREAD

**Issue by robertzeibich** [bwa-mem2/bwa-mem2#233]
I am getting to different outputs when using bwa-mem2 and bwa/0.7.17:
**bwa-mem2**
<img width="618" alt="bwa-mem2" src="https://github.com/bwa-mem2/bwa-mem2/assets/73748542/ec5e9e37-f1e2-4477-b2ee-a68277bf19a1">

**bwa/0.7.17**
<img width="563" alt="bwa_0 7 17" src="https://github.com/bwa-mem2/bwa-mem2/assets/73748542/adf9ce04-557f-4128-8b80-ee0f41f7414b">

For both output, I used the same pipeline:
1. fq2sam --> `bwa mem -t ${threads} -R ${rg} ${FASTA} ${R1} ${R2} > ${samfile}` OR `bwa-mem2 mem -t ${threads} -R ${rg} ${FASTA} ${R1} ${R2} > ${samfile`}
2. sam2bam using picard.jar SortSam
3. mark duplicates using picard.jar MarkDuplicates
4. base recalibration and apply bqsr using gatk BaseRecalibrator and gatk ApplyBQSR

There is a input difference for the fasta files:

**bwa-mem2**
![image](https://github.com/bwa-mem2/bwa-mem2/assets/73748542/7b05c22b-a051-4374-8bc2-5678cb561f18)
I used bwa-mem2 index on the fasta to create the index files.

**bwa/0 7 17**
![image](https://github.com/bwa-mem2/bwa-mem2/assets/73748542/b0981e86-745b-454f-93c6-78ef748cf9a6)

I used gatk CreateSequenceDictionary -R on the fasta to have the .dic file created and with samtools faidx , I created the .fai file.

Based on the bwa-mem2 github, the output of bwa-mem2 should match with the original bwa-mem version 0.7.17.

The output does not match. Do you know why? 

Help is much appreciated. 

I am looking forward to hearing back from you.

**Comment by vasimuddin** [comment]
bwa index does not produce .fai file. can you check the bwa sam output diff? if it still differs then pls. provide/point to the exact command line and the reads files.

**Comment by serge2016** [comment]
I hope there is now such a difference... Could you check twice, please?

**Comment by robertzeibich** [comment]
Most probably that the alt file is not used.

**Comment by yuk12** [comment]
@robertzeibich closing the issue. Please re-open if the issue still persists.
