### ISSUE TITLE
error "SSE4.1 instruction set not enabled"

### ISSUE THREAD

**Issue by dzaccook** [bwa-mem2/bwa-mem2#25]
Hi,
I get an error when make the code,

g++ -c -g -O3 -fpermissive   -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/fastmap.cpp -o src/fastmap.o
In file included from src/bandedSWA.h:42:0,
                 from src/bwamem.h:39,
                 from src/fastmap.h:45,
                 from src/fastmap.cpp:39:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/smmintrin.h:31:3: error: #error "SSE4.1 instruction set not enabled"
 # error "SSE4.1 instruction set not enabled"
   ^
make: *** [src/fastmap.o] Error 1

What is the problem?
Thank you!

**Comment by dzaccook** [comment]
I make a older version and it passed, but when I running mapping, I get another error,
bwa-mem2: src/fastmap.cpp:253: ktp_data_t* kt_pipeline(void*, int, void*, mem_opt_t*, worker_t&): Assertion `ret->n_seqs <= nreads' failed.
Can you give me some help?
Thank you!

**Comment by yuk12** [comment]
Please provide machine details: Processor number, OS, memory.

For some reason arch flag is missing here:
g++ -c -g -O3 -fpermissive **-msse4.1** -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0 src/fastmap.cpp -o src/fastmap.o

**Comment by johnsCheng** [comment]
also is my problem.
`make
g++ -c -g -O3 -fpermissive   -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1                                                                                              -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/fastmap.cpp -o src/fastma                                                                                             p.o
`where no the `-msse4.1` assertion,
my machine info:Intel(R) Xeon(R) Gold 6130; CentOS 7.6.1810; 256GB
any help? thanks!

**Comment by sanchit-misra** [comment]
@johnsCheng What command are you using to compile the code?

**Comment by dzaccook** [comment]
This is the info: CentOS Linux release 7.5.1804 (Core); 6  Intel Xeon Processor (Skylake); MemTotal:       15878216 kB.
Thank you!

**Comment by sanchit-misra** [comment]
It looks like the machine has ~16GB memory. That is too low to run bwa-mem2 for full human genome. As mentioned in the README-ori.md, the index itself needs about 35-40 GB memory.

**Comment by dzaccook** [comment]
This node is just used to submit jobs, it tells an error when make the code, "/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/smmintrin.h:31:3: error: #error "SSE4.1 instruction set not enabled".
The nodes to run bwa-mem2 have 256Gb memory.

**Comment by sanchit-misra** [comment]
@dzaccook @johnsCheng I fixed one bug in the Makefile. Now you should see -msse4.1 when compiling without specifying any value of arch. Specifically, if you use the following command to compile:
$ make

We recommend you use the value of arch that is appropriate for the architecture you are planning to run on. For example, for avx2 enabled architecture, use:
$ make arch=avx2

If you don't know what architecture the code will run on, you can use:
$ make arch=multi
and it will compile for multiple kinds of architecture and will detect automatically.

**Comment by dzaccook** [comment]
It works, thank you!
