### ISSUE TITLE
Add option to align multiple .fastq files at once?

### ISSUE THREAD

**Issue by bskubi** [bwa-mem2/bwa-mem2#257]
Our lab is working with single-cell data, which is often aligned after demultiplexing and removing barcodes, and is sometimes in the format of thousands of .fastq files.

This poses a problem for bwa-mem2, because it takes about 20 seconds to start up each instance and consumes substantial memory. With 10,000 .fastq files, it adds days to alignment time. This poses an even greater challenge when validating pipelines, as that alignment process may need to be done multiple times, using tiny test datasets where the time to start up bwa-mem2 is the bottleneck.

How seriously would the developers consider adding a feature to supply multiple .fastqs or pairs of .fastqs, aligning them all with the same parameters and outputting multiple .sam files, one for each result?

I'm considering building a utility to remultiplex .fastq files applying a file-specific barcode to each read, aligning the batch once, then demultiplex at the end. This is non-ideal, especially since bwa-mem2 can use statistics on the .fastq files to inform how it aligns them, but it's critical for my purposes to find a solution for this problem.

Devs, please let me know if you think you might make a solution for this problem in the near-term. If not, that's OK! Thanks for your great work on this project.

Edit - perhaps what would be most ideal would be adding the ability to run bwa-mem2 in a client-server model, permitting bwa-mem2 to receive new inputs at any time.

**Comment by vasimuddin** [comment]
Do you still need this?

**Comment by bskubi** [comment]
Yes, I managed to hack together something that sort-of works for me personally, but I'd like to include it as part of a pipeline and it would be really nice to have an official solution.

Having a version that let's you batch multiple single or paired end fastq files would be a good 90% solution.

I wound up making a solution that let's bwa-mem2 run as a daemon program aligning submitted jobs at any time, which is even better for my needs.

What I wasn't able to solve is making it produce the same results each time without restarting from scratch. In about 5-10% of alignments, it gives a different primary alignment. I don't think it's due to the random number generator calls in bwa-mem2 but is maybe due to either some aspect of threading or due to something about how the data structures are modified during alignment.

If you guys do make an official solution I would be very glad to use it.
