### ISSUE TITLE
src/bwamem.cpp:662 error

### ISSUE THREAD

**Issue by ziyou722** [bwa-mem2/bwa-mem2#26]
Hi, 
I get the Error message:
readLen: 120

[0000] 1: Calling process()

Threads used (compute): 32
Projected #read in a task: 2666676
------------------------------------------
Memory pre-allocation for chaining: 85482965856
Memory pre-allocation for BSW: 7667744768
Memory pre-allocation for BWT: 1572933632
------------------------------------------
No. of pipeline threads: 2
[0000] read_chunk: 320000000, work_chunk_size: 320000191, nseq: 2320440
	[0000][ M::kt_pipeline] read 2320440 sequences (320000191 bp)...
[0000] 2. Calling mem_process_seqs.., task: 0
[0000] 3. Calling kt_for - worker_bwt
bwa-mem2: src/bwamem.cpp:662: SMEM* mem_collect_smem(const mem_opt_t*, const bseq1_t*, int, SMEM*, int32_t*, int16_t*, uint8_t*, int32_t*, int64_t&): Assertion `query_pos_ar[pos] < len' failed.

nothing to output but the core file ~130G (core dumped).  How  can I fix this error?

**Comment by yuk12** [comment]
Please try with the latest commit and let us know. Thanks.

**Comment by ziyou722** [comment]
There's no problem with the latest version.
Thank you.

**Comment by yuk12** [comment]
Cool. Thanks for the confirmation. Closing the issue.
