### ISSUE TITLE
Error in AVX2 mode

### ISSUE THREAD

**Issue by xingchen0120** [bwa-mem2/bwa-mem2#27]
Hi,
First of all, thank you for creating bwa-mem2. It is a very cool tool.
I met a problem when I tried to execute in AVX2 mode.
make arch=avxw
./bwa-mem2 mem hg38.fa XXX.fastq
Executing in AVX2 mode!
Ref file:.....
Entering FMI_search
reference seq_len = 
segmentation fault (core dumped)

**Comment by yuk12** [comment]
Can you share the complete log, along with the command-line you used? Thanks.

**Comment by xingchen0120** [comment]
Sure.
command-line I used:
make arch=avxw
./bwa-mem2 mem hg38.fa ERR194147.fastq

log ：
__________
Executing in AVX2 mode!!
___________
Ref file : hg38.fa
Entering FMI_search
reference seq_len = 6418572211
Segmentation fault(core dumped)

by the way, can i get other log except for the message printed on the screen

**Comment by xingchen0120** [comment]
> Can you share the complete log, along with the command-line you used? Thanks.

Sure.
command-line I used:
make arch=avxw
./bwa-mem2 mem hg38.fa ERR194147.fastq

log ：

Executing in AVX2 mode!!

Ref file : hg38.fa
Entering FMI_search
reference seq_len = 6418572211
Segmentation fault(core dumped)

by the way, can i get log form other place except for the message printed on the screen?

**Comment by sanchit-misra** [comment]
Did you create the index first using the following?
./bwa-mem2 index hg38.fa

Also, bwa-mem2 does not support a value of arch equal to avxw. If you want to use avx2, please compile using:
make arch=avx2

**Comment by xingchen0120** [comment]
> Did you create the index first using the following?
> ./bwa-mem2 index hg38.fa
> 
> Also, bwa-mem2 does not support a value of arch equal to avxw. If you want to use avx2, please compile using:
> make arch=avx2

Thanks for your help
I crated index at first.  I am sorry for my spelling mistake. I used the compile command: make arch = avx2 not avxw.
But it still doesn't work.

**Comment by sanchit-misra** [comment]
Could you please specify the processor, available memory and compiler version you are using?

**Comment by fwip** [comment]
I am also seeing this, or a related issue.

GCC: 5.3.0
Processor:  Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (Haswell family; feature flags contain `avx2` )
bwa-mem2 commit: `6f21de2873a892207c4d315a3a0e59cfffb0b71b` (at time of writing, this is master)
OS: CentOS Linux, 7.4.1708
Available memory: 500GB

Compilation: `make multi`

When executing `./bwa-mem2`, it selects AVX2 (I believe correctly). It then segfaults after printing out the reference size, as described by @xingchen0120.

Running with GDB reveals the crashing line to be here: https://github.com/bwa-mem2/bwa-mem2/blob/master/src/FMI_search.cpp#L72 (`count[ii] = count[ii] +1`). `count` is `{1, 1817861263, 3099922541, 4381983819, 6199845082}`, `ii` is "optimized out."

That's about as far as my debugging knowledge can take me.  Compiling with `-O0` appears to segfault slightly later in the program.

I will attempt to compile this with ICPC instead, to see what the behavior is like there.

**Comment by sanchit-misra** [comment]
@xingchen0120 Were you also using gcc? 
@fwip I could reproduce this on gcc in AVX2 mode. It works fine with icpc. For some weird reason, gcc had a problem with us declaring a 256 byte array class variable. I have replaced it with a pointer and the seg fault is gone.
