### ISSUE TITLE
Error during mapping: query_pos_ar[pos] < len' failed

### ISSUE THREAD

**Issue by AndrewCarroll** [bwa-mem2/bwa-mem2#3]
First, thank you for your work on this important program. I am looking forward to the improvements in BWA MEM2.

Running BWA MEM2 with the pre-built binaries results in the following for me:

bwa-mem2: src/bwamem.cpp:662: smem_struct *mem_collect_smem(const mem_opt_t *, const bseq1_t *, int, smem_struct *, int *, short *, unsigned char *, int *, long &): Assertion `query_pos_ar[pos] < len' failed.

The machine is Intel Skylake n1-standard-32 on GCP (32 core, 120GB RAM).

Reference genome: GRCh38.no_alt_analysis_set.fa.gz
Index generated: ./bwa-mem2 index GRCh38.no_alt_analysis_set.fa.gz
Input files - NA12878-I30 NovaSeq WGS from BaseSpace (the first 10,000 reads of each pair can reproduce the issue).  These files are attached.

Command and error:
```text
time ./bwa-mem2 mem ../references/GRCh38.no_alt_analysis_set.fa.gz NA12878-I30.10000r.R1.fastq.gz NA12878-I30.10000r.R2.fastq.gz -t 32 -R '@RG\tID:NA12878-I30\tLB:NA12878-I30\tPL:ILLUMINA\tPU:NONE\tSM:NA12878' | samtools sort -O BAM -o NA12878.bam -

Entering FMI_search
reference seq len = 6199845083
count
0,      1
1,      1817861264
2,      3099922542
3,      4381983820
4,      6199845083

Reading other elements of the index from files ../references/GRCh38.no_alt_analysis_set.fa.gz
prefix: ../references/GRCh38.no_alt_analysis_set.fa.gz
[M::bwa_idx_load_ele] read 0 ALT contigs
Done reading Index!!
Reading reference genome..
Binary seq file = ../references/GRCh38.no_alt_analysis_set.fa.gz.0123
Reference genome size: 6199845082 bp
Done readng reference genome !!

readLen: 150

[0000] 1: Calling process()

Threads used (compute): 32
Projected #read in a task: 2133343
------------------------------------------
Memory pre-allocation for chaining: 68386443208
Memory pre-allocation for BSW: 7667744768
Memory pre-allocation for BWT: 1966149632
------------------------------------------
No. of pipeline threads: 2
[0000] read_chunk: 320000000, work_chunk_size: 3008555, nseq: 20000
        [0000][ M::kt_pipeline] read 20000 sequences (3008555 bp)...
[0000] 2. Calling mem_process_seqs.., task: 0
[0000] 3. Calling kt_for - worker_bwt
[0000] read_chunk: 320000000, work_chunk_size: 0, nseq: 0
bwa-mem2: src/bwamem.cpp:662: smem_struct *mem_collect_smem(const mem_opt_t *, const bseq1_t *, int, smem_struct *, int *, short *, unsigned char *, int *, long &): Assertion `query_pos_ar[pos] < len' failed.

[NA12878-I30.10000r.R2.fastq.gz](https://github.com/bwa-mem2/bwa-mem2/files/3205601/NA12878-I30.10000r.R2.fastq.gz)
[NA12878-I30.10000r.R1.fastq.gz](https://github.com/bwa-mem2/bwa-mem2/files/3205602/NA12878-I30.10000r.R1.fastq.gz)
```

**Comment by lh3** [comment]
Are these reads of the same length? Or some reads are shorter and some longer?

**Comment by godotgildor** [comment]
It looks like the reads do vary.  Most are around 150 or 151 bp, but there are some reads that are in the 35 - 40 bp reads.  I found that if one filters all reads but those that have both fwd and rev = 151 bp, the assert will be avoided.  (Note that this leaves 4024 reads out of the original 10,000).

**Comment by lh3** [comment]
> It looks like the reads do vary.

I have realized this based on the average read length: 3008555/20000=150.4bp. Thanks for the confirmation anyway. This is a bug. Bwa-mem2 assumes all reads are of the same length. #1 is likely to be caused by the same issue. @yuk12 and @sanchit-misra are working on this.

**Comment by godotgildor** [comment]
Thanks @lh3 , @yuk12 , and @sanchit-misra !

**Comment by AndrewCarroll** [comment]
Ah, thanks to everyone on this thread. You are all faster to the reply than me.

Yes, the read lengths do vary here, but the input was not preprocessed in an unusual way. The FASTQ files are directly from BaseSpace, so I presume their generation is standard. Thanks to all for looking at this.

**Comment by ahstram** [comment]
I'm able to reproduce this issue using a pair of small variable-read-length NA12878 FASTQ files from 1000 Genomes:

> ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data/NA12878/sequence_read/SRR002631_1.filt.fastq.gz
> ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data/NA12878/sequence_read/SRR002631_2.filt.fastq.gz

Here's the command to reproduce, using the above files:

`bwa-mem2.avx512bw mem -K 10000000 -t 8 hs37d5.fa SRR002631_1.filt.fastq.gz SRR002631_2.filt.fastq.gz`

**Comment by jcgrenier** [comment]
Got the same error here. In fact, we are preprocessing the reads in order to remove any adaptors or bad quality end on the reads. Thanks for looking into this!

**Comment by mp15** [comment]
It would be useful if there were some way to tell BWA on a per read basis we've hardclipped x number of bases from a given read (or better still allow us to leave the bases on and have BWA mark them as softclipped).

**Comment by sanchit-misra** [comment]
@AndrewCarroll This bug should have been solved. Could you please try the latest code from the repo?

**Comment by ivargr** [comment]
I had the same issue and can confirm that this is fixed after compiling the latest code from this repo.

**Comment by AndrewCarroll** [comment]
I can confirm that this is fixed for me. Thank you for your help with this!
