### ISSUE TITLE
Dec 12th commit ICPC pre-compiled?

### ISSUE THREAD

**Issue by kingralph80** [bwa-mem2/bwa-mem2#31]
Dear authors,

I just used the latest commit (Dec 12, 2019), as gcc compiled version, for our GATK pipeline and it finally runs stable and produced comparable results to our bwa-mem pipeline. I have tried the previous versions with very issues posted here. Would it be possible to offer the latest commit as ICPC compiled binaries to optimize the speed?

Cheers,
Thomas

**Comment by sanchit-misra** [comment]
Yes, we are planning to do a new release soon.

**Comment by yuk12** [comment]
We have released a new version. Please try that.
