### ISSUE TITLE
Unequal sequences lead to segment fault

### ISSUE THREAD

**Issue by qiuwancen** [bwa-mem2/bwa-mem2#32]
I used a fastq sequence of varying length to align with the reference genome and obtained segment errors.

**Comment by sanchit-misra** [comment]
Are you using the latest commit?

**Comment by qiuwancen** [comment]
I used the precompiled binaries .

发件人: sanchit-misra <notifications@github.com>
发送时间: 2019年12月26日 19:17
收件人: bwa-mem2/bwa-mem2 <bwa-mem2@noreply.github.com>
抄送: 邱婉岑(Wancen Qiu) <qiuwancen@genomics.cn>; Author <author@noreply.github.com>
主题: Re: [bwa-mem2/bwa-mem2] Unequal sequences lead to segment fault (#32)


Are you using the latest commit?

**Comment by sanchit-misra** [comment]
This bug is fixed. Please try the latest commit.
