### ISSUE TITLE
Assertion failed on mem_collect_smem

### ISSUE THREAD

**Issue by MagpiePKU** [bwa-mem2/bwa-mem2#33]
Hi,

We compiled the latest commit of bwa-mem2 with g++ (our icpc does not work somehow):
make -j20 multi ARCH_FLAGS=-mavx2
 and used it in bwa-meth pipeline which pipes C-to-T converted fastq on the fly into bwa. 

Note the index has been built with the same bwa-mem2 on a c-to-T converted genome "v37_decoy_plus_phage.fasta.bwameth.c2t" 

We got an assertion failure which (by reading the readme) might due to memory allocation problem. 

The error log is:

///
-----------------------------
Executing in AVX2 mode!!
-----------------------------
Ref file: /gpfs/genomedb/b37/b37_bwamem2/v37_decoy_plus_phage.fasta.bwameth.c2t
Entering FMI_search
reference seq len = 12550012029
count
0,	1
1,	4851497105
2,	6275006015
3,	7698514925
4,	12550012029

Reading other elements of the index from files /gpfs/genomedb/b37/b37_bwamem2/v37_decoy_plus_phage.fasta.bwameth.c2t
prefix: /gpfs/genomedb/b37/b37_bwamem2/v37_decoy_plus_phage.fasta.bwameth.c2t
[M::bwa_idx_load_ele] read 0 ALT contigs
Done reading Index!!
Reading reference genome..
Binary seq file = /gpfs/genomedb/b37/b37_bwamem2/v37_decoy_plus_phage.fasta.bwameth.c2t.0123
Reference genome size: 12550012028 bp
Done readng reference genome !!

readLen: 97

[0000] 1: Calling process()

Threads used (compute): 16
Projected #read in a task: 1649494
------------------------------------------
Memory pre-allocation for chaining: 52876179664
Memory pre-allocation for BSW: 3833872384
Memory pre-allocation for BWT: 635734016
------------------------------------------
No. of pipeline threads: 2
[0000] read_chunk: 160000000, work_chunk_size: 160000216, nseq: 1357552
	[0000][ M::kt_pipeline] read 1357552 sequences (160000216 bp)...
[0000] 2. Calling mem_process_seqs.., task: 0
[M::kt_pipeline] 0 single-end sequences; 1357552 paired-end sequences.....
[0000] 3. Calling kt_for - worker_bwt
bwa-mem2: src/bwamem.cpp:662: smem_struct *mem_collect_smem(const mem_opt_t *, const bseq1_t *, int, smem_struct *, int *, short *, unsigned char *, int *, long &): Assertion `query_pos_ar[pos] < len' failed.

///

The readme file states that one could increase the values of corresponding macros but we would like to know exactly where and how to tweak... 

Thanks a lot in ahead.

Best,
Yi

**Comment by yuk12** [comment]
This doesn't look like the latest commit. can you try with the latest one and let us know?
