### ISSUE TITLE
Occasionally hitting Segmentation Fault

### ISSUE THREAD

**Issue by yihhwang** [bwa-mem2/bwa-mem2#35]
Setting:

- Binary built using commit 091cf8a
- Ran on AWS c5d.9xlarge with Linux-4.4.0-1092-aws-x86_64 and Ubuntu-16.04-xenial
- Executing in AVX512 mode

Note:
- A rerun may or may not hit Segmentation Fault. It was around 50:50 chance on finishing the mapping successfully or hitting Segmentation Fault.

Log (Segmentation Fault):
```
⟫ bwa-mem2 mem -t 36 genome/hs38DH.fa /home/dnanexus/in/reads_fastqgzs/0/ERR2990063_1.fastq.gz /home/dnanexus/in/reads2_fastqgzs/0/ERR2990063_2.fastq.gz -K 100000000 -Y -R '@RG\tID:ERR2990063_1\tPL:ILLUMINA\tPU:ERR2990063_1\tLB:ERR2990063\tSM:ERR2990063' > /dev/null
-----------------------------
Executing in AVX512 mode!!
-----------------------------
Ref file: genome/hs38DH.fa
Entering FMI_search
reference seq len = 6434693835
... [Deleted for brievity]
[0000] 3. Calling kt_for - worker_bwt
[0000] read_chunk: 100000000, work_chunk_size: 7276690, nseq: 48190
        [0000][ M::kt_pipeline] read 48190 sequences (7276690 bp)...
[0000] 3. Calling kt_for - worker_aln
Inferring insert size distribution from data, l_pac: 3217346917, n: 662252
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (3, 279551, 4, 4)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (240, 282, 341)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (38, 543)
[M::mem_pestat] mean and std.dev: (294.94, 74.25)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 644)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[0000] 10. Calling kt_for - worker_sam
        [0000][ M::mem_process_seqs] Processed 662252 reads in 104.068 CPU sec, 3.060 real sec
[0000] 2. Calling mem_process_seqs.., task: 46
[0000] 3. Calling kt_for - worker_bwt
[0000] 3. Calling kt_for - worker_aln
Segmentation fault
139

```

Below are the files we used:
Reference genome (hs38DH.fa as a tar file): https://dl.dnanex.us/F/D/jG73Z8595GxZYXpKJbqGZzJyX15Q3V0YQG96BxJ7/hs38DH.bwa-index.avx512.v2.tar.gz
ERR2990063_1.fastq.gz: https://dl.dnanex.us/F/D/7Z6ygpJ3xVzf7bG04gx4JVPZ2y4G842g52fJJ9B9/ERR2990063_1.fastq.gz 
ERR2990063_2.fastq.gz: https://dl.dnanex.us/F/D/8545B424zVg53Y3BKFyzXxXbJzJV1f3X6KP8V84g/ERR2990063_2.fastq.gz
STDOUT/STDERR of the run:
https://dl.dnanex.us/F/D/pv3VqJyv1842gkk0G45Q0qv362PqvP12J20G61ZX/ERR2990063.log

**Comment by yuk12** [comment]
Can you try with the latest commit and check.

**Comment by yihhwang** [comment]
I tried b1e436c and consistently got **Segmentation Fault** every time (>3 times for paired-end mapping, and >2 times for single-end mapping) with this set of input.

You can find the input FASTQ and reference files I used in the original message, if you are interested in reproducing the issue. 

Ran on AWS c5d.9xlarge with Linux-4.4.0-1092-aws-x86_64 and Ubuntu-16.04-xenial
Executing in AVX512 mode

Paired-ended input:
```
$ bwa-mem2 mem -t 72 genome/hs38DH.fa /home/dnanexus/in/reads_fastqgzs/0/ERR2990063_1.fastq.gz -K 100000000 -Y -R '@RG\tID:ERR2990063_1\tPL:ILLUMINA\tPU:ERR2990063_1\tLB:ERR2990063\tSM:ERR2990063' > output.sam
-----------------------------
Executing in AVX512 mode!!
-----------------------------
Ref file: genome/hs38DH.fa
Entering FMI_search
reference seq len = 6434693835
count
0,      1
1,      1882204624
2,      3217346918
3,      4552489212
4,      6434693835

Reading other elements of the index from files genome/hs38DH.fa
prefix: genome/hs38DH.fa
[M::bwa_idx_load_ele] read 0 ALT contigs
Done reading Index!!
Reading reference genome..
Binary seq file = genome/hs38DH.fa.0123
Reference genome size: 6434693834 bp
Done readng reference genome !!

[0000] 1: Calling process()

Threads used (compute): 72
Info: projected #read in a task: 662261
------------------------------------------
Memory pre-allocation for chaining: 1393.3971 MB
Memory pre-allocation for BSW: 17252.4257 MB
Memory pre-allocation for BWT: 5566.6207 MB
------------------------------------------
No. of pipeline threads: 2
[0000] read_chunk: 100000000, work_chunk_size: 100000052, nseq: 662252
        [0000][ M::kt_pipeline] read 662252 sequences (100000052 bp)...
[0000] 2. Calling mem_process_seqs.., task: 0
[0000] 3. Calling kt_for - worker_bwt
Segmentation fault
```


Single-ended input:
```
$ bwa-mem2 mem -t 36 genome/hs38DH.fa /home/dnanexus/in/reads_fastqgzs/0/ERR2990063_1.fastq.gz -K 100000000 -Y -R '@RG\tID:ERR2990063_1\tPL:ILLUMINA\tPU:ERR2990063_1\tLB:ERR2990063\tSM:ERR2990063' > output.sam
-----------------------------
Executing in AVX512 mode!!
-----------------------------
Ref file: genome/hs38DH.fa
Entering FMI_search
reference seq len = 6434693835
count
0,      1
1,      1882204624
2,      3217346918
3,      4552489212
4,      6434693835

Reading other elements of the index from files genome/hs38DH.fa
prefix: genome/hs38DH.fa
[M::bwa_idx_load_ele] read 0 ALT contigs
Done reading Index!!
Reading reference genome..
Binary seq file = genome/hs38DH.fa.0123
Reference genome size: 6434693834 bp
Done readng reference genome !!

[0000] 1: Calling process()

Threads used (compute): 36
Info: projected #read in a task: 662261
------------------------------------------
Memory pre-allocation for chaining: 1393.3971 MB
Memory pre-allocation for BSW: 8626.2129 MB
Memory pre-allocation for BWT: 2783.3103 MB
------------------------------------------
No. of pipeline threads: 2
[0000] read_chunk: 100000000, work_chunk_size: 100000052, nseq: 662252
        [0000][ M::kt_pipeline] read 662252 sequences (100000052 bp)...
[0000] 2. Calling mem_process_seqs.., task: 0
[0000] 3. Calling kt_for - worker_bwt
Segmentation fault
```

Also, a minor point, there is a typo at `Done readng reference genome !!` -- should be "read**i**ng" instead of "readng".

**Comment by yuk12** [comment]
Commits after 6743183 need rebuilding the index, as mentioned in the readme.
did you try that?
We have also released a new version, you can also try that and check.

**Comment by yihhwang** [comment]
For the single-ended input, it finished successfully after using the rebuilt reference genome index.
```
$ bwa-mem2 mem -t 72 genome/hs38DH.fa /home/dnanexus/in/reads_fastqgzs/0/ERR2990063_1.fastq.gz -K 100000000 -Y -R '@RG\tID:ERR2990063_1\tPL:ILLUMINA\tPU:ERR2990063_1\tLB:ERR2990063\tSM:ERR2990063' > /dev/null
```

However, there is still segmentation fault with exit code 139 when using the rebuilt index when inputting paired-end reads:
```
$ bwa-mem2 mem -t 72 genome/hs38DH.fa /home/dnanexus/in/reads_fastqgzs/0/ERR2990063_1.fastq.gz /home/dnanexus/in/reads2_fastqgzs/0/ERR2990063_2.fastq.gz -K 100000000 -Y -R '@RG\tID:ERR2990063_1\tPL:ILLUMINA\tPU:ERR2990063_1\tLB:ERR2990063\tSM:ERR2990063'  > /dev/null
-----------------------------
Executing in AVX512 mode!!
-----------------------------
Ref file: genome/hs38DH.fa
Entering FMI_search
reference seq len = 6434693835
count
0,      1
1,      1882204624
2,      3217346918
3,      4552489212
4,      6434693835

Reading other elements of the index from files genome/hs38DH.fa
prefix: genome/hs38DH.fa
[M::bwa_idx_load_ele] read 0 ALT contigs
Done reading Index!!
Reading reference genome..
Binary seq file = genome/hs38DH.fa.0123
Reference genome size: 6434693834 bp
Done readng reference genome !!

[0000] 1: Calling process()

Threads used (compute): 72
Info: projected #read in a task: 662261
------------------------------------------
Memory pre-allocation for chaining: 1393.3971 MB
Memory pre-allocation for BSW: 17252.4257 MB
Memory pre-allocation for BWT: 5566.6207 MB
------------------------------------------
No. of pipeline threads: 2
[[ ... detailed log removed for simplicity... ]]
Inferring insert size distribution from data, l_pac: 3217346917, n: 662252
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 279429, 5, 2)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (239, 281, 339)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (39, 539)
[M::mem_pestat] mean and std.dev: (293.83, 73.61)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 639)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[0000] 10. Calling kt_for - worker_sam
        [0000][ M::mem_process_seqs] Processed 662252 reads in 138.352 CPU sec, 2.223 real sec
[0000] read_chunk: 100000000, work_chunk_size: 100000052, nseq: 662252
        [0000][ M::kt_pipeline] read 662252 sequences (100000052 bp)...
[0000] 2. Calling mem_process_seqs.., task: 45
[0000] 3. Calling kt_for - worker_bwt
[0000] read_chunk: 100000000, work_chunk_size: 7276690, nseq: 48190
        [0000][ M::kt_pipeline] read 48190 sequences (7276690 bp)...
[0000] 3. Calling kt_for - worker_aln
Inferring insert size distribution from data, l_pac: 3217346917, n: 662252
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (3, 279551, 4, 4)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (240, 282, 341)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (38, 543)
[M::mem_pestat] mean and std.dev: (294.94, 74.25)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 644)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[0000] 10. Calling kt_for - worker_sam
        [0000][ M::mem_process_seqs] Processed 662252 reads in 143.204 CPU sec, 2.288 real sec
[0000] 2. Calling mem_process_seqs.., task: 46
[0000] 3. Calling kt_for - worker_bwt
[0000] 3. Calling kt_for - worker_aln
[LOG] [0131] Re-allocating seqPairArrays Right
[LOG] [0132] Re-allocating seqPairArrays Right
[LOG] [0133] Re-allocating seqPairArrays Right
Segmentation fault
139 $
```

**Comment by yuk12** [comment]
How much memory does your system have?
I am suspecting that it is running out of memory. 

I am able to successfully run bwa-mem2 on the datasets given by you. Here is my output log.

$ ./bwa-mem2 mem -t 72 /scratch/omics/index/human/ref/hs38DH/hs38DH.fa /scratch/omics/index/human/reads/ERR2990063_1.fastq.gz /scratch/omics/index/human/reads/ERR2990063_2.fastq.gz -K 100000000 -Y -R '@RG\tID:ERR2990063_1\tPL:ILLUMINA\tPU:ERR2990063_1\tLB:ERR2990063\tSM:ERR2990063'  > /dev/null
-----------------------------
Executing in AVX512 mode!!
-----------------------------
Ref file: /scratch/omics/genomes-indexes-reads/human/ref/hs38DH/hs38DH.fa
Entering FMI_search
reference seq len = 6418915857
count
0,      1
1,      1877984092
2,      3209457929
3,      4540931766
4,      6418915857

Reading other elements of the index from files /scratch/omics/genomes-indexes-reads/human/ref/hs38DH/hs38DH.fa
prefix: /scratch/omics/genomes-indexes-reads/human/ref/hs38DH/hs38DH.fa
[M::bwa_idx_load_ele] read 0 ALT contigs
Done reading Index!!
Reading reference genome..
Binary seq file = /scratch/omics/genomes-indexes-reads/human/ref/hs38DH/hs38DH.fa.0123
Reference genome size: 6418915856 bp
Done readng reference genome !!

[0000] 1: Calling process()

Threads used (compute): 72
Info: projected #read in a task: 662261
------------------------------------------
Memory pre-allocation for chaining: 1393.3971 MB
Memory pre-allocation for BSW: 17252.4257 MB
Memory pre-allocation for BWT: 5566.6207 MB
------------------------------------------
No. of pipeline threads: 2
[0000] read_chunk: 100000000, work_chunk_size: 100000052, nseq: 662252
        [0000][ M::kt_pipeline] read 662252 sequences (100000052 bp)...
[0000] 2. Calling mem_process_seqs.., task: 0
[0000] 3. Calling kt_for - worker_bwt
[0000] 3. Calling kt_for - worker_aln
Inferring insert size distribution from data, l_pac: 3209457928, n: 662252
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 0, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[0000] 10. Calling kt_for - worker_sam
        [0000][ M::mem_process_seqs] Processed 662252 reads in 68.051 CPU sec, 1.578 real sec
[...Intermediate tasks log....]
[0000] 2. Calling mem_process_seqs.., task: 46
[0000] 3. Calling kt_for - worker_bwt
[0000] 3. Calling kt_for - worker_aln
Inferring insert size distribution from data, l_pac: 3209457928, n: 48190
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 0, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[0000] 10. Calling kt_for - worker_sam
        [0000][ M::mem_process_seqs] Processed 48190 reads in 5.345 CPU sec, 0.134 real sec
[0000] read_chunk: 100000000, work_chunk_size: 0, nseq: 0
[0000] read_chunk: 100000000, work_chunk_size: 0, nseq: 0
[0000] Computation ends..

**Comment by sanchit-misra** [comment]
@yihhwang The memory used is directly proportional to # threads used. So, if you are running out of memory, try with smaller number of threads.

**Comment by yihhwang** [comment]
@sanchit-misra, After reducing number of thread used to a lower number, the segmentation fault went away, and mapping finished successfully. 

Is it possible to further constrain of memory usage? In the ideal world, we would like to utilize maxima the numbers of threads on the instance to exhaustive the resource and optimize speed whenever possible. 

It seems that some samples require more memory than most of the other samples. For example, this sample, ERR2990063, which has 30.7 million reads and read length as 151bb, required more than 144GB of memory on a 72-core (c5d.18xlarge), and more than 72GB of memory on a 36-core (c5d.9xlarge). While another sample, ERR2990093 (access below), with similar profile as ERR2990063, does not have the same issue. I was wondering if there were some characteristics of the reads triggering the memory issue? Any thoughts?

https://dl.dnanex.us/F/D/FgQBzgxk7VfjF9J95fPF453fFXg397z8vbfbPpy6/ERR2990093_1.fastq.gz
https://dl.dnanex.us/F/D/zpvg73pQp43JG9Pq1BGP7QB6JfKbxzBQqY68qv0j/ERR2990093_2.fastq.gz

**Comment by yuk12** [comment]
Yes, it is possible but at the cost of performance. We will consider the suggestion.
