### ISSUE TITLE
What do we do of the different executables?

### ISSUE THREAD

**Issue by aderzelle** [bwa-mem2/bwa-mem2#36]
Hello, 
I guess a simple question but what would be the difference between running 

`bwa-mem2 mem`
VS
`bwa-mem2.avx2 mem`

On a proc supporting AVX2 instructions? Is the first executable a kind of wrapper that would identify the correct architecture? 

Thank you

**Comment by lh3** [comment]
Yes, if you compile with `make multi`, bwa-mem2 is merely a wrapper that selects the optimal executables among bwa-mem2.avx2 etc.
