### ISSUE TITLE
c_bcast_array error

### ISSUE THREAD

**Issue by xijiang** [bwa-mem2/bwa-mem2#37]
Hi, if I just run `make` on my amd3900x, there are some warnings and an error message (log shown at the end). `make arch=avx2` ran smoothly.

Warning and error messages:
src/bwamem.cpp: In function ‘void mem_chain2aln_across_reads_V2(const mem_opt_t*, const bntseq_t*, const uint8_t*, bseq1_t*, int, mem_chain_v*, mem_alnreg_v*, mem_cache*, int64_t, int64_t, int64_t, int)’:
src/bwamem.cpp:2016:37: warning: invalid conversion from ‘int’ to ‘_mm_hint’ [-fpermissive]
 2016 |   _mm_prefetch((const char*) query, 0);
      |                                     ^
      |                                     |
      |                                     int
In file included from /usr/lib/gcc/x86_64-redhat-linux/9/include/emmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/pmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/tmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/smmintrin.h:32,
                 from src/bandedSWA.h:42,
                 from src/bwamem.h:39,
                 from src/bwamem.cpp:31:
/usr/lib/gcc/x86_64-redhat-linux/9/include/xmmintrin.h:52:46: note:   initializing argument 2 of ‘void _mm_prefetch(const void*, _mm_hint)’
   52 | _mm_prefetch (const void *__P, enum _mm_hint __I)
      |                                ~~~~~~~~~~~~~~^~~
src/bwamem.cpp:2034:51: warning: invalid conversion from ‘int’ to ‘_mm_hint’ [-fpermissive]
 2034 |    _mm_prefetch((const char*) (srtg + spos + 64), 0);
      |                                                   ^
      |                                                   |
      |                                                   int
In file included from /usr/lib/gcc/x86_64-redhat-linux/9/include/emmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/pmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/tmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/smmintrin.h:32,
                 from src/bandedSWA.h:42,
                 from src/bwamem.h:39,
                 from src/bwamem.cpp:31:
/usr/lib/gcc/x86_64-redhat-linux/9/include/xmmintrin.h:52:46: note:   initializing argument 2 of ‘void _mm_prefetch(const void*, _mm_hint)’
   52 | _mm_prefetch (const void *__P, enum _mm_hint __I)
      |                                ~~~~~~~~~~~~~~^~~
src/bwamem.cpp:2035:40: warning: invalid conversion from ‘int’ to ‘_mm_hint’ [-fpermissive]
 2035 |    _mm_prefetch((const char*) (lim_g), 0);
      |                                        ^
      |                                        |
      |                                        int
In file included from /usr/lib/gcc/x86_64-redhat-linux/9/include/emmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/pmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/tmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/smmintrin.h:32,
                 from src/bandedSWA.h:42,
                 from src/bwamem.h:39,
                 from src/bwamem.cpp:31:
/usr/lib/gcc/x86_64-redhat-linux/9/include/xmmintrin.h:52:46: note:   initializing argument 2 of ‘void _mm_prefetch(const void*, _mm_hint)’
   52 | _mm_prefetch (const void *__P, enum _mm_hint __I)
      |                                ~~~~~~~~~~~~~~^~~
src/bwamem.cpp:2072:37: warning: invalid conversion from ‘int’ to ‘_mm_hint’ [-fpermissive]
 2072 |    _mm_prefetch((const char*) rseq, 0);
      |                                     ^
      |                                     |
      |                                     int
In file included from /usr/lib/gcc/x86_64-redhat-linux/9/include/emmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/pmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/tmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/smmintrin.h:32,
                 from src/bandedSWA.h:42,
                 from src/bwamem.h:39,
                 from src/bwamem.cpp:31:
/usr/lib/gcc/x86_64-redhat-linux/9/include/xmmintrin.h:52:46: note:   initializing argument 2 of ‘void _mm_prefetch(const void*, _mm_hint)’
   52 | _mm_prefetch (const void *__P, enum _mm_hint __I)
      |                                ~~~~~~~~~~~~~~^~~
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/profiling.cpp -o src/profiling.o
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/bandedSWA.cpp -o src/bandedSWA.o
src/bandedSWA.cpp: In member function ‘void BandedPairWiseSW::smithWatermanBatchWrapper16(SeqPair*, uint8_t*, uint8_t*, int32_t, uint16_t, int8_t)’:
src/bandedSWA.cpp:3755:63: warning: invalid conversion from ‘int’ to ‘_mm_hint’ [-fpermissive]
 3755 |      _mm_prefetch((const char*) seqBufRef + (int64_t)spf.idr, 0);
      |                                                               ^
      |                                                               |
      |                                                               int
In file included from /usr/lib/gcc/x86_64-redhat-linux/9/include/emmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/pmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/tmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/smmintrin.h:32,
                 from src/bandedSWA.h:42,
                 from src/bandedSWA.cpp:30:
/usr/lib/gcc/x86_64-redhat-linux/9/include/xmmintrin.h:52:46: note:   initializing argument 2 of ‘void _mm_prefetch(const void*, _mm_hint)’
   52 | _mm_prefetch (const void *__P, enum _mm_hint __I)
      |                                ~~~~~~~~~~~~~~^~~
src/bandedSWA.cpp:3756:68: warning: invalid conversion from ‘int’ to ‘_mm_hint’ [-fpermissive]
 3756 |      _mm_prefetch((const char*) seqBufRef + (int64_t)spf.idr + 64, 0);
      |                                                                    ^
      |                                                                    |
      |                                                                    int
In file included from /usr/lib/gcc/x86_64-redhat-linux/9/include/emmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/pmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/tmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/smmintrin.h:32,
                 from src/bandedSWA.h:42,
                 from src/bandedSWA.cpp:30:
/usr/lib/gcc/x86_64-redhat-linux/9/include/xmmintrin.h:52:46: note:   initializing argument 2 of ‘void _mm_prefetch(const void*, _mm_hint)’
   52 | _mm_prefetch (const void *__P, enum _mm_hint __I)
      |                                ~~~~~~~~~~~~~~^~~
src/bandedSWA.cpp:3799:63: warning: invalid conversion from ‘int’ to ‘_mm_hint’ [-fpermissive]
 3799 |      _mm_prefetch((const char*) seqBufQer + (int64_t)spf.idq, 0);
      |                                                               ^
      |                                                               |
      |                                                               int
In file included from /usr/lib/gcc/x86_64-redhat-linux/9/include/emmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/pmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/tmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/smmintrin.h:32,
                 from src/bandedSWA.h:42,
                 from src/bandedSWA.cpp:30:
/usr/lib/gcc/x86_64-redhat-linux/9/include/xmmintrin.h:52:46: note:   initializing argument 2 of ‘void _mm_prefetch(const void*, _mm_hint)’
   52 | _mm_prefetch (const void *__P, enum _mm_hint __I)
      |                                ~~~~~~~~~~~~~~^~~
src/bandedSWA.cpp:3800:68: warning: invalid conversion from ‘int’ to ‘_mm_hint’ [-fpermissive]
 3800 |      _mm_prefetch((const char*) seqBufQer + (int64_t)spf.idq + 64, 0);
      |                                                                    ^
      |                                                                    |
      |                                                                    int
In file included from /usr/lib/gcc/x86_64-redhat-linux/9/include/emmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/pmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/tmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-redhat-linux/9/include/smmintrin.h:32,
                 from src/bandedSWA.h:42,
                 from src/bandedSWA.cpp:30:
/usr/lib/gcc/x86_64-redhat-linux/9/include/xmmintrin.h:52:46: note:   initializing argument 2 of ‘void _mm_prefetch(const void*, _mm_hint)’
   52 | _mm_prefetch (const void *__P, enum _mm_hint __I)
      |                                ~~~~~~~~~~~~~~^~~
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/FMI_search.cpp -o src/FMI_search.o
src/FMI_search.cpp: In destructor ‘FMI_search::~FMI_search()’:
src/FMI_search.cpp:129:14: error: ‘c_bcast_array’ was not declared in this scope
  129 |     _mm_free(c_bcast_array);
      |              ^~~~~~~~~~~~~
make: *** [Makefile:75: src/FMI_search.o] Error 1

**Comment by sanchit-misra** [comment]
That was a bug. Thanks for pointing it out. Fixed in commit b1e436c.
