### ISSUE TITLE
support for uBam input?

### ISSUE THREAD

**Issue by eboyden** [bwa-mem2/bwa-mem2#38]
Hi - I know the team isn't currently focused on adding features, but it would be great to add support for uBam input.  This is increasingly the recommended workflow (e.g. by GATK/Picard team) since uBams can store metadata e.g. UMIs that are not easily stored or parsed in fastqs, and is increasingly supported by other popular aligners e.g. Novoalign and Bowtie 2.

**Comment by lh3** [comment]
The recommended practice is to stream fastq and copy over annotations with -C.

**Comment by eboyden** [comment]
Illumina's bcl2fastq puts UMIs in the main header, not in the comment.  Unfortunately most software including Picard and fgbio can only parse UMIs in Sam tags, yet no common software I have found has a tool to move them from read headers into tags (umi-tools claims to have this functionality but it doesn't work with PE data).  I contacted the Samtools and Picard teams to suggest that they add support for parsing UMIs in read headers and moving them to Sam tags, and both teams said that instead of using bcl2fastq I should be doing bcl > uBam in order to put the UMIs into Sam tags directly; from there I can stream a uBam to a fastq, align it, and then combine the mapped and unmapped Bams to reconstitute the tag metadata.  But it would be simpler to be able to align uBams directly and not have to stream fastqs or combine bams.  Like I said I realize this isn't where the focus currently is, but it would be nice to add when time allows.

**Comment by lh3** [comment]
You can copy the UMI to read comments with a script while streaming. In general, I don't like to support vendor-specific features that are changing all the time. I attempt to provide mechanism flexible enough for users to implement their own vendor-specific code on their end.

**Comment by lh3** [comment]
You can copy tags to fastq with "samtools fastq -T" and then bwa mem can copy these tags to output SAM with "-C". That is one pass. You don't need to "reconstitute the tag metadata".

**Comment by matthdsm** [comment]
Hi @lh3 

Do you mean to say that using `samtools fastq -T` + `bwa-mem2 mem -C` is equal to mapping and merging ubam + bam?
If so, that seems preferable over using the merge step at the end.

Thanks
M
