### ISSUE TITLE
Do you plan a support for long reads (ONT, PacBio) as in the original bwa mem?

### ISSUE THREAD

**Issue by lpryszcz** [bwa-mem2/bwa-mem2#4]
Previous bwa mem version supported long reads through present settings (-x). Do you plan to introduce it here as well?

**Comment by lh3** [comment]
The option is still their in the code. It is just that the command line help doesn't show it. Nonetheless, minimap2 is and will be the preferred mapper for long reads. Bwa-mem2 is only optimized for short reads.
