### ISSUE TITLE
Refgenome indexing suffix array failed

### ISSUE THREAD

**Issue by dgomezpere** [bwa-mem2/bwa-mem2#41]
Hi,

I am migrating from the original bwa to bwa-mem2 and I am trying unsuccessfully to generate the indexes for the reference genome *GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna.gz*, available at:

`ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna.gz`

The output is:

```
$ bwa-mem2 index GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna 
[bwa_index] Pack FASTA... 9.78 sec
init ticks = 177097768626
ref seq len = 6211430126
binary seq ticks = 121988005759
Allocation of 46.28 GB for suffix_array failed.
Current Allocation = 52.06 GB
```

The output is the same in different machines indexing this reference genome.

Indexing the same genome with original bwa does not report any error.

**Comment by matryoskina** [comment]
I'm having the same problem. Try to index a 6 Gb genome on a cluster. 
I get this:

[bwa_index] Pack FASTA... 27.74 sec
init ticks = 481684733588
ref seq len = 12823204788
binary seq ticks = 266742218400

And that's it

**Comment by tomaskopsa** [comment]
I have got the same error:

$ bwa-mem2 index GCF_000001405.39_GRCh38.p13_genomic.fna 
[bwa_index] Pack FASTA... 8.57 sec
init ticks = 207347185858
ref seq len = 6544178410
binary seq ticks = 231926360206
Allocation of 48.76 GB for suffix_array failed.
Current Allocation = 54.85 GB

**Comment by lh3** [comment]
These are probably caused by insufficient memory. I would recommend ~128GB memory for indexing human and more for larger genomes. Mapping uses less memory.

**Comment by tomaskopsa** [comment]
Thank you for explanation, my workstration has only 32 GB. I'll index reference at another server.

**Comment by dgomezpere** [comment]
Thank you very much for the feedback Heng!!
I'll try bwa-mem2 when I have access to more resources.
Another question, is it enough 64GB for mapping 250x WES human data??

**Comment by serge2016** [comment]
Dear @lh3, are you planning to make it possible to index human genome on a machine with 32 GB RAM or even less?

**Comment by yuk12** [comment]
@dgomezpere You need 28N GB space for creating the index, where N is the length of the reference sequence. Mapping requires less memory.
@serge2016 No. The performance gain of bwa-mem2 over bwa-mem depends on larger index.

**Comment by Nitin123-4** [comment]
Allocation of 21.72 GB for cp_occ failed.
I am also getting the same issue even when I am running it in 256 GB RAM server

**Comment by UniverFish** [comment]
Hi, Dear Sir or Mandam,
I installed bwa-mem2 in the Ubun subsystem through conda, but I also encountered this problem when indexing the human genome([Homo_sapiens.GRCh38.dna.toplevel.fa.gz](https://ftp.ensembl.org/pub/release-109/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.toplevel.fa.gz)-----SIZE-57GB)
Server: CPU: 36 cores. RAM: 256GB, HDD Size: 12t

bwa-mem2 index Homo_sapiens.GRCh38.dna.toplevel.faooking to launch executable”/miniconda3/bin/bwa-mem2.avx2”， simd = .avx2aunching executable”/miniconda3/bin/bwa-mem2.avx2bwa index] 
Pack FASTA... 894.20 sec
Entering FlI searchinit ticks = 5412253740629ref seq 
len = 126294395496binary seq 
ticks = 5851901309383
Allocation of 940.97 GB for suffix_array failed.
Current A1location = 1058.59 GBODECkTODTL.11

**Comment by sanchit-misra** [comment]
Hi @UniverFish 
Is the genome size expected to be 57 GB? If it is, then both strands of the genome in your case are adding up to 126 billion bases (126294395496). That is needing a memory allocation of ~940 GB, significantly larger than the 256 GB memory the machine has. 

But human genome is typically 3 gigabases. Also, the file (Homo_sapiens.GRCh38.dna.toplevel.fa.gz) is only 1 GB in size. So, its not possible that it has 57 Gigabases of sequence. So, something seems off.

**Comment by UniverFish** [comment]
> Hi @UniverFish Is the genome size expected to be 57 GB? If it is, then both strands of the genome in your case are adding up to 126 billion bases (126294395496). That is needing a memory allocation of ~940 GB, significantly larger than the 256 GB memory the machine has.
> 
> But human genome is typically 3 gigabases. Also, the file (Homo_sapiens.GRCh38.dna.toplevel.fa.gz) is only 1 GB in size. So, its not possible that it has 57 Gigabases of sequence. So, something seems off.

Thank you for your attention and reply.
I downloaded the human genome .gz file (1GB) from the ensembl database, and the decompressed size is really large, showing 62,695,026 KB (~57GB) in the win11 system.I'm not sure if it's the right way to unzip it. At the same time, the genome index can be successfully constructed using bwa index(FILE SIZE.png).

![FILE SIZE](https://user-images.githubusercontent.com/107673131/220100091-d8d2eb84-c466-4449-abcd-2d1c05371346.png)

Best regards.

**Comment by UniverFish** [comment]
OK. I circumvented this large memory requirement problem by switching to a reference genome and downloading it from UCSC instead of ensembl.
https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/latest/hg38.fa.gz.
