### ISSUE TITLE
Assertion `reference_seq_len > 0' failed

### ISSUE THREAD

**Issue by DBS-Max** [bwa-mem2/bwa-mem2#43]
Hi,

I am using the precompiled version 2.0pre2 and built the index using `bwa-mem2 index` for Grch38. I am now trying to align but get the error:

```
-----------------------------
Executing in AVX512 mode!!
-----------------------------
Ref file: /reference/GRCh38_full_analysis_set_plus_decoy_hla.fa
Entering FMI_search
bwa-mem2: src/FMI_search.cpp:56: FMI_search::FMI_search(char *): Assertion `reference_seq_len > 0' failed.
```

The command looks like:

```
docker run \
    -v /media/maxh/fast_storage/1x_reads:/data \
    -v /media/maxh/slow_storage/human_data/reference_genome/mem2_index:/reference \
    cannabinoid/bwa-mem2:0.1 bwa-mem2 mem \
        /reference/GRCh38_full_analysis_set_plus_decoy_hla.fa \
        /data/ERR3239279_R1_1x.fastq.gz \
        /data/ERR3239279_R2_1x.fastq.gz 
```

It is detecting the indices because if I run with a malformed reference path it gives a different error.

I am going to try and rebuild the indices, will update when this is complete.

**Comment by DBS-Max** [comment]
So, I seem to have just not enough RAM, I have 80GB, do I need more?
 Is there a pre-computed GRCH38.p1 index available?

**Comment by yuk12** [comment]
You need >84 GB memory to build the index. 
About the pre-computed index: No, we don't have as of now.
