### ISSUE TITLE
AMD Compatibility with AVX2

### ISSUE THREAD

**Issue by cnk113** [bwa-mem2/bwa-mem2#48]
Hello,

I'm not that knowledgeable about AVX compilation processes so I was wondering what parameters do I change in the Makefile to make it compatible with AVX2 AMD CPUs?
Using the precompiled binaries gives me an error about using compatible AVX CPUs, and the makefile fails to get AVX2 to build.

Best,
Chang

**Comment by sanchit-misra** [comment]
You can compile for AMD CPUs with AVX2 using the following:
make arch=-march=core-avx2 CXX=icpc
