### ISSUE TITLE
subtle differences in alignment when compared to bwa 0.7.17-r1188

### ISSUE THREAD

**Issue by ahstram** [bwa-mem2/bwa-mem2#5]
Hi there,

It appears that there are some small differences in alignment when invoking bwa-mem2 vs bwa version 0.7.17-r1188.

To demonstrate, I obtained a pair of NA12878 FASTQ files from 1000 Genomes:
> ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data/NA12878/sequence_read/ERR001713_1.filt.fastq.gz
> ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data/NA12878/sequence_read/ERR001713_2.filt.fastq.gz

I then invoked both the bwa and bwa-mem2 as follows:
```
$ bwa mem -K 10000000 -t 8 hs37d5.fa ERR001713_1.filt.fastq.gz ERR001713_2.filt.fastq.gz  | samtools view -u - > bwa.bam
$ bwa-mem2 mem -K 10000000 -t 8 hs37d5.fa ERR001713_1.filt.fastq.gz ERR001713_2.filt.fastq.gz  | samtools view -u - > bwa-mem2.bam
```
Now, when looking at the "samtools stats" output for each BAM file, there are some subtle differences:
```
$ diff <(samtools stats bwa.bam | grep '^SN') <(samtools stats bwa-mem2.bam | grep '^SN')
20c20
< SN	bases mapped (cigar):	284761502	# more accurate
---
> SN	bases mapped (cigar):	284761501	# more accurate
23,24c23,24
< SN	mismatches:	1854434	# from NM fields
< SN	error rate:	6.512235e-03	# mismatches / bases mapped (cigar)
---
> SN	mismatches:	1854433	# from NM fields
> SN	error rate:	6.512232e-03	# mismatches / bases mapped (cigar)
```

And here's one example of a slightly different alignment:
```
$ samtools view bwa.bam  | grep '^ERR001713.5425457'
ERR001713.5425457	83	6	83350583	0	7S29M	=	83350484	-128	ACTAGAAAAATCCAATAGCATATCAAAAAGATAATC	(4&;-7>>>>4;,>>9>1<&>;<-7><>>><;<>;<	NM:i:1	MD:Z:28A0	MC:Z:36M	AS:i:28	XS:i:29
ERR001713.5425457	163	6	83350484	0	36M	=	83350583	128	TACCAAAACCAGGAATGGACATAACAAAAAAAGAAA	<;><;<>>><>7.<89.<49;9>,87;>><5.8&5+	NM:i:1	MD:Z:15A20	MC:Z:7S29M	AS:i:31	XS:i:31
$ samtools view bwa-mem2.bam  | grep '^ERR001713.5425457'
ERR001713.5425457	83	13	102092425	0	8S28M	=	102092325	-128	ACTAGAAAAATCCAATAGCATATCAAAAAGATAATC	(4&;-7>>>>4;,>>9>1<&>;<-7><>>><;<>;<	NM:i:0	MD:Z:28	AS:i:28	XS:i:29
ERR001713.5425457	163	13	102092325	0	36M	=	102092425	128	TACCAAAACCAGGAATGGACATAACAAAAAAAGAAA	<;><;<>>><>7.<89.<49;9>,87;>><5.8&5+	NM:i:1	MD:Z:15A20	AS:i:31	XS:i:31
```
That is, in the first read of "ERR001713.5425457", the soft clipping differs by one basepair.

Are these subtle differences in alignments between bwa and bwa-mem2 to be expected?

**Comment by sanchit-misra** [comment]
Could you please specify the machine you are using? Which processor?

**Comment by sanchit-misra** [comment]
Also, the program prints whether it is using AVX512, AVX2, SSE or scalar mode. Could you please let us know which mode is being used?

**Comment by mp15** [comment]
I am not sure the specific example you give is anything to worry about? That looks to me like mapping quality 0 telomeric sequence? I suspect something is just slightly perturbing the random seed that BWA uses. (see this article: https://standage.github.io/reproducible-variant-calling-is-possible-with-randomized-algorithms.htm)

**Comment by ahstram** [comment]
@sanchit-misra this was done using both the pre-compiled "bwa-mem2" and "bwa-mem2.avx512bw" binaries (version bwa-mem2-2.0pre1_x64-linux), using "Intel(R) Xeon(R) Gold 6146 CPU @ 3.20GHz" CPUs.

@mp15 I agree the differences are subtle, but it does break the threshold of "identical". Differing results, even subtle differences, requires us to re-validate our pipelines before being able to put bwa-mem2 into production. That's a lot of work.

**Comment by mp15** [comment]
I would argue this is a problem with the rules not the software; perhaps tweak the rules by recognising that these differences are not relevant to your objective? Requiring exactly identical mappings on reads lacking sufficient genomic context gains little and is likely to be an impediment to speed increases. Additionally making both scientific and clinical decisions based on mapping quality 0 reads would be questionable and most pipelines filter these reads out as differences between them are irreconcilable noise.

It is also worth noting that BWA MEM 0.7.x will give different results for MapQ 0 on the same input if you change the chunk size, thread count or the order you supply the reads (by using collate rather than sort for example).

**Comment by sanchit-misra** [comment]
@ahstram Could you try using the latest code from the repo? I believe that should solve the problem.

**Comment by sanchit-misra** [comment]
I have been able to reproduce this with the latest commit. Will look into it.

**Comment by sanchit-misra** [comment]
I have not been able to reproduce this with the latest commit. Hence, I am closing this issue.
