### ISSUE TITLE
the sam file cannot be recognized 

### ISSUE THREAD

**Issue by Yixiangzhang1996** [bwa-mem2/bwa-mem2#52]
nohup ./bwa-mem2 
the sam file cannot be recognized when I use samtools to convert to bam file

` 
[W::sam_read1] Parse error at line 1
[main_samview] truncated file.
`

**Comment by yuk12** [comment]
What command line & data did you use to generate the sam file?

**Comment by yuk12** [comment]
@Yixiangzhang1996: closing it. plz re-open if you are still facing the issue.

**Comment by AJK91** [comment]
I have similar problem when using bwa-mem2 (v 2.2.1) to generate sam file with the command
 bwa-mem2 mem ref forward.fq reverse.fq > aligned.sam
afterwards when checking the sam file with samtools flagstat aligned.sam I get 

[W::sam_read1_sam] Parse error at line 802361
samtools flagstat: error reading from "RS0106.normal.sam"

I use  samtools 1.15.1
Does anyone know what is the reason for this?
