### ISSUE TITLE
Mapping to a portion of reference genome

### ISSUE THREAD

**Issue by a00101** [bwa-mem2/bwa-mem2#54]
I have a one question on splitted reference genome.

I firstly mapped PE-WG sequence files to whole genome. Its output is about 80GB.
and then i splitted reference genome into only chr22 (the shortest chromosome) and mapped files to splitted genome.
But Its output is about 80GB at the same above.

Do i need to process something?

Thanks.

**Comment by lh3** [comment]
Bwa outputs unmapped reads as well. Please have a look at your output.

**Comment by a00101** [comment]
wow. thank you for your rapid answer.

Can i use this command for extracting mapped reads?
`
samtools view -bF 0x04 out.bam > mapped.bam
`

**Comment by lh3** [comment]
You can, but it is advised not to map reads to a single chr. This will lead to severe artifacts.

**Comment by a00101** [comment]
You meanm, is it better to split to a single chromosome after mapping it to the entire chromosome?

**Comment by lh3** [comment]
*Always* maps to the entire chr.
