### ISSUE TITLE
Which icpc version was used for provided binaries?

### ISSUE THREAD

**Issue by keiranmraine** [bwa-mem2/bwa-mem2#55]
Hi,

Please can you indicate which version of icpc was used to build the v2.0pre2 binaries.  We are seeing ~10% slowdown when we compile with 19.0.4.235.

Thanks,
Keiran

**Comment by sanchit-misra** [comment]
icpc (ICC) 18.0.3 20180410

**Comment by lh3** [comment]
@keiranmraine do you mean the binary from the release page? I compiled it on a CentOS6 machine with icc 19.0.3.199.

**Comment by keiranmraine** [comment]
Yes, thats what I was after.  I've since had a few repeats of the exact same job run and I'm now seeing that 10% appears to be a natural variability so there must be some disk/network or other non-obvious factor causing this.

**Comment by keiranmraine** [comment]
Would you recommend icc over icpc:

> Invoking the compiler using icc compiles .c and .i files  as  C.
>       Using icpc always links in C++ libraries.  Using icc only links in C++
 >      libraries if C++ source is provided on the command line.
