### ISSUE TITLE
include `-5` option from original bwa mem

### ISSUE THREAD

**Issue by mcshane** [bwa-mem2/bwa-mem2#56]
Is is possible to add the `-5` option  (for split alignment, take the alignment with the smallest coordinate as primary) from the original bwa mem?

**Comment by yuk12** [comment]
bwa-mem2 supports all the command line options supported by bwa-mem. I don't see `-5`. can you provide more details?

**Comment by mcshane** [comment]
From the manpage:

-5        For split alignment, mark the segment with the smallest coordinate as the primary. It automatically applies option -q as well. This option may help some Hi-C pipelines. By default, BWA-MEM marks highest scoring segment as primary.

**Comment by yuk12** [comment]
I did not realize that it is a new addition in bwa-0.7.17 version.
We have added the features (-5 and -q flags) in bwa-mem2. 
Let us know if you face the issue or see the performance impact.

**Comment by mcshane** [comment]
Great. Thanks. Will test it and file another issue if there are any issue that arise.
