### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by tfmorris** [bwa-mem2/bwa-mem2#58]
Is there a timeline for when this will be considered production ready? 

A ~50% savings in time / money / energy is pretty significant for such a widely used tool.

**Comment by serge2016** [comment]
Nice question! It would be great to see the next release!

**Comment by sanchit-misra** [comment]
The code is pretty much ready for production. We are working with Heng for the final confirmation.

**Comment by serge2016** [comment]
Thank you! We are waiting!
