### ISSUE TITLE
Potential memory leak?

### ISSUE THREAD

**Issue by godotgildor** [bwa-mem2/bwa-mem2#6]
I've been running some tests on a set of 30x WGS samples.  I have been trying to run the sample on a c5d.9xlarge on AWS which has ~69 GB free RAM when I launch (~2 GB per core).  So far, all of my attempts have failed to complete the mapping.  The log doesn't contain any OOM errors but I have made the following observations:
1. The run will complete without issue on a m5d.12xlarge which has ~190 GB of RAM (~4 GB per core).
2. On the c5d.9xlarge, when mapping starts, it is initially using ~59 GB of RAM.  Every few minutes, the RAM usage increases monotonically by about 1 GB.  Towards the end of the run it is very close to the 69 GB total free - leading me to believe it is terminating because it runs out of RAM.  

I then ran Intel's Inspector tool on the executable to look for potential memory leaks.  The tool identified a few potential issues:
1. In bwamem.cpp line 397, there is a calloc call and the resulting buffer is assigned to c->seeds.  However, it doesn't appear, at least in this location, that any previous buffer was freed.  
2. In bwamem.cpp line 400 there is a realloc call that is then assigned to c->seeds.  Realloc should free the buffer it's trying to reallocate if needed but...
3. ... on my test run of just around 1,000,000 reads, Intel Inspector lists potential memory leads from the calloc call 73 times and the from the realloc call 66 times affecting 15,039,104 bytes.

I tried the naive thing of just checking if c->seed is not NULL and if it's not, calling
`free(c->seed)`
just before we set c->seed to the new auxSeedBuf buffer, right around line 398, but it looks like that's not quite right since I get an error message about free being called against an invalid pointer.  

In case it is helpful, the results of the Intel Inspector run can be found in the tar file here:
https://dl.dnanex.us/F/D/Qbk7Jz49kB51828xbYgB9KQGXVx4gK71VGvzBvqv/bwa_intel_inspector_project.tar.gz

**Comment by yuk12** [comment]
Thanks for reporting. There were some seeds not getting deallocated. We have fixed that.

**Comment by godotgildor** [comment]
Thanks @yuk12.  With commit 02e9413 I no longer saw the memory leak.  I'll close this issue.
