### ISSUE TITLE
Alignment quality to HLA and ALT region

### ISSUE THREAD

**Issue by NTNguyen13** [bwa-mem2/bwa-mem2#61]
Hi, I'm interested in testing BWA-MEM2 for my project at this time, however after reading this benchmark: https://blog.dnanexus.com/2020-03-10-bwa-mem2-review/, I wonder about the current quality of ALT and HLA alignment, because I mainly work on those regions.

Has any further improvement been implemented so far?

Thank you

**Comment by yuk12** [comment]
We are trying to reproduce the issues. I did some quick runs on the a few mentioned datasets and could not reproduce it. But we are now doing some more testing ( and DNAnexus folks are generously helping us in trying to reproduce the issues).  We intend to resolve this very quickly.
In the meantime, you can go ahead test it out yourself, and let us know if you face any difficulty.

**Comment by yihchii** [comment]
Hi @NTNguyen13, with the latest binary generated from a commit ~20 days ago, we found the results between BWA-MEM2 and BWA-MEM2 are identical for hs38DH (GRCh38 primary contigs + decoy contigs + ALT contigs and HLA genes). Read more on the [blog post](https://blog.dnanexus.com/2020-03-10-bwa-mem2-review/) with our update note made today.

**Comment by NTNguyen13** [comment]
Thank you for nice update, however I haven't found the update section in the link you posted

**Comment by yihchii** [comment]
@NTNguyen13 Please find the update note as the first section of the post, or ctrl+F (command+F for Mac users) and search for _"Update June 11th, 2020_".
