### ISSUE TITLE
Memory requirements

### ISSUE THREAD

**Issue by zamaudio** [bwa-mem2/bwa-mem2#64]
Hi, bwa-mem2 seems to use a lot more RAM than bwa 0.7.x.

What are the expected memory requirements for bwa-mem2 while running (not indexing, I realise indexing takes quite a chunk of RAM)?

It seems to be using ~44G of memory for 8 threads and reducing the thread count does not seem to reduce the memory requirements for a human genome alignment.  Is this expected?

Thanks.

**Comment by mp15** [comment]
Yes, it is a classical speed-memory tradeoff. In BWA MEM2 compared to BWA MEM the suffix array lookup was sped up 183x by replacing the compressed suffix array with an uncompressed one (see https://arxiv.org/pdf/1907.12931.pdf for details of how this was done).
