### ISSUE TITLE
Please include ext/safestringlib in a source tarball and add to the GitHub release

### ISSUE THREAD

**Issue by mr-c** [bwa-mem2/bwa-mem2#66]
Debian relies upon getting a complete source tarball and alas the GitHub auto-generated tarballs don't include git submodules.

Can you make a complete archive and add it as an additional asset to https://github.com/bwa-mem2/bwa-mem2/releases/tag/v2.0 (and future releases)?

Thanks!

**Comment by sanchit-misra** [comment]
Done

**Comment by mr-c** [comment]
Thanks for the quick fix @sanchit-misra !
