### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by asmlgkj** [bwa-mem2/bwa-mem2#7]
Dear professor,
I get an error when using mem2, can you give me some advice, thanks a lot
![image](https://user-images.githubusercontent.com/50854682/58865249-d1172380-86e8-11e9-8e78-f63880a3f552.png)

**Comment by KimBioInfoStudio** [comment]
hi, which platform did u using ? and what s the cpu model name ? and how much memory did it have?   
should u split raw data a small piece and try if pass  maybe case by out of memory error I think

**Comment by asmlgkj** [comment]
I use centos.
it has 126G memory 
cpu model name:  Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz.
I think the memory is enough.
thanks a lot

**Comment by yuk12** [comment]
@asmlgkj could you try with the latest commit and let us know.
Thanks.

**Comment by asmlgkj** [comment]
four hours passed, bwa index still not ended, I used hg19.
thanks a lot

**Comment by asmlgkj** [comment]
@yuk12 
Thanks a lot. it is ok now

**Comment by WengangxJJ** [comment]
Hi yuk12,
I just take away this thread. I came across the same issue. 
The bwa-mem2 is 2.1 version.
![bwamem2](https://user-images.githubusercontent.com/57957118/99921252-0ec69c80-2d21-11eb-89fe-cfe5dc2a7d39.png)
it has 126GB RAM and CPU is Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
And the user has no RAM limited
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 514163
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

It would be great if you could have a look on this . Many thanks in advance.
Wengang
