### ISSUE TITLE
bwa-mem2 fails to choose proper executable

### ISSUE THREAD

**Issue by shah-rohan** [bwa-mem2/bwa-mem2#70]
Using the 2.0.0 release precompiled binary on an Ubuntu 18.04 system with Intel Xeon processors.

The command `bwa-mem2` yields the following error: `ERROR: fail to find the right executable`.

Running the executable `bwa-mem2.avx512bw` yields the following message: `Please verify that both the operating system and the processor support Intel(R) MOVBE, F16C, FMA, BMI, LZCNT, AVX2, AVX512DQ, AVX512F, ADX, AVX512CD, AVX512BW, AVX512VL and CLWB instructions.`

Output from other two executables appears normal.

**Comment by sanchit-misra** [comment]
Same as #73
