### ISSUE TITLE
cannot find strcpy_s function

### ISSUE THREAD

**Issue by kemin711** [bwa-mem2/bwa-mem2#76]
src/fastmap.cpp: In function ‘int main_mem(int, char**)’:
src/fastmap.cpp:858:5: error: ‘strcpy_s’ was not declared in this scope
     strcpy_s(binary_seq_file, PATH_MAX, argv[optind]);
     ^~~~~~~~

**Comment by kemin711** [comment]
31 #define __STDC_WANT_LIB_EXT1__ 1

Add this line to fastmap.cpp removed the bug

**Comment by kemin711** [comment]
My problem is probably with my gnu compiler not supporting strcpy_s function.  One of my solution is to convert it into C++ code from C code.

**Comment by sanchit-misra** [comment]
strcpy_s is available in safestringlib which is a submodule of bwa-mem2. You don't need the C++ version if you did the part highlighted in bold:
# Get the source
git clone **--recursive** https://github.com/bwa-mem2/bwa-mem2
cd bwa-mem2
# Or
git clone https://github.com/bwa-mem2/bwa-mem2
cd bwa-mem2
**git submodule init
git submodule update**

**Comment by kemin711** [comment]
Sorry forgot the recursive option.
