### ISSUE TITLE
Reproducing results

### ISSUE THREAD

**Issue by JensHuthmann** [bwa-mem2/bwa-mem2#79]
Hello, I am interested in reproducing the results you showed in the README.md. However, as I come from a different background than bioinformatics it is hard to understand how the create the same input files you were using. Could you add an description on how to download/create (some of) the datasets?

**Comment by yuk12** [comment]
Except for dataset D1, remain datasets described in the README are public datasets available on NCBI SRA repository.
https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software#header-global
To download these datasets you can use their SRA Toolkit. Once you download the toolkit, you can use ```fastq-dump``` command of it to download D2, D3, D4 datasets. The documentation of the toolkit and command is available on the above link. You can use ```fastq-dump``` command to download first 2x2.5M reads for the experiments.

**Comment by JensHuthmann** [comment]
Did you filter the resulting _.fasta_ for limiting the length to 151bp? fastq-dump has no such option as far as I can see. If so what tool did you use?

Also what was the reference sequence you used for the matching of the datasets? From https://github.com/bwa-mem2/bwa-mem2/blob/master/README-ori.md I am guessing it is _hg38.fa_.

**Comment by yuk12** [comment]
By default the read length for these reads is 151bp.
The reference genome used for the runs was "human_g1k_v37.fasta"  (Thanks for pointing out).

Also, please note: 
If you are using a machine with multiple sockets and numa domains, please use numactl to run on single socket (numa domain) for maximum performance.
E.g: In dual numa and dual socket system: numactl -m 0 -N 0 <bwa-mem2> command executes bwa-mem2 on first socket and numa domain.

I have update the README.md.

**Comment by yuk12** [comment]
@JensHuthmann I've added more detailed steps in README. Please refer to it.
