### ISSUE TITLE
Sam header missing newline between user provided @RG line and @PG line

### ISSUE THREAD

**Issue by godotgildor** [bwa-mem2/bwa-mem2#8]
I'm specifying read group information at the command line and am noticing that in the SAM header output, there is no new line inserted between my read group information line and the following @PG line.  Looking at the code, I see that there appears to be a #if statement that would lead to a path of code that would include the newline and another path that results in no newline:
https://github.com/bwa-mem2/bwa-mem2/blob/30a633dd06ddb0e480664fce65894f7c28d011d0/src/bwa.cpp#L543-L553

Was there a reason for omitting the newline in the second path?

**Comment by yuk12** [comment]
Thanks for pointing out the issue, it is fixed now.

**Comment by godotgildor** [comment]
Thanks!
