### ISSUE TITLE
Can old BWA alt files be used?

### ISSUE THREAD

**Issue by rhpvorderman** [bwa-mem2/bwa-mem2#81]
For example the alt file in ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_full_plus_hs38d1_analysis_set.fna.bwa_index.tar.gz ? 

Or does a separate alt file need to be created? If so, what is the process? Should a different procedure for creating the index be followed when using the `.alt` file?

**Comment by rhpvorderman** [comment]
Looking at the [blog post from DNA Nexus](https://blog.dnanexus.com/author/yih-chii-hwang-jason-chin/) where they assess the performance of BWA-mem2. It seems that they used the [run-gen-ref script from BWA](https://github.com/lh3/bwa/blob/3a2b0c05ddeacea2785bbd3935cc3d3861f28751/bwakit/run-gen-ref#L13) to get the genomes.

In that script the `.alt` file is clearly provided upstream, while the index is later created.

I am therefore going to assume:
1. Old BWA `.alt` files can be used.
2. No different procedure for creating the index is necessary.

If you can confirm this is the case, I will write some documentation about this in a PR so future users can more easily find this knowledge.

**Comment by yuk12** [comment]
Yes, the old alt file works.

**Comment by rhpvorderman** [comment]
Thanks a lot @yuk12 !
