### ISSUE TITLE
Fail to find the right executable

### ISSUE THREAD

**Issue by Poshi** [bwa-mem2/bwa-mem2#86]
I just downloaded the pre-compiled version (as advised, https://github.com/bwa-mem2/bwa-mem2/releases/download/v2.0/bwa-mem2-2.0_x64-linux.tar.bz2) and untarred the contents.
I also added the folder to the PATH, just to be sure it can find it's other executables.

When I try to run the software, I get the following error:
```
$ bwa-mem2
ERROR: fail to find the right executable
```

In order to get some insight on what it is looking for, I run it through strace. Here I who the last (and most relevant lines):
```
$ strace bwa-mem2 2>&1 | tail
stat("/home/user/bin/bwa-mem2", 0x7ffebb14e780) = -1 ENOENT (No such file or directory)
stat("/home/user/src/bwa-mem2-2.0_x64-linux/bwa-mem2", {st_mode=S_IFREG|0755, st_size=29848, ...}) = 0
stat("/home/user/src/bwa-mem2-2.0_x64-linux/bwa-mem2.sse42", 0x7ffebb14e540) = -1 ENOENT (No such file or directory)
stat("/home/user/src/bwa-mem2-2.0_x64-linux/bwa-mem2.sse42.sse41", 0x7ffebb14e5d0) = -1 ENOENT (No such file or directory)
stat("/home/user/src/bwa-mem2-2.0_x64-linux/bwa-mem2.sse42.sse41.sse2", 0x7ffebb14e660) = -1 ENOENT (No such file or directory)
stat("/home/user/src/bwa-mem2-2.0_x64-linux/bwa-mem2.sse42.sse41.sse2.sse", 0x7ffebb14e6f0) = -1 ENOENT (No such file or directory)
write(2, "ERROR: fail to find the right ex"..., 41ERROR: fail to find the right executable
) = 41
exit_group(2)                           = ?
+++ exited with 2 +++
```
It look like it is searching for a set of binaries that are not present. I'm not sure if they should be there, or the names generated should be different.
Either case, it would be good to also have a fallback, so the user can run the code despite not using a highly optimized version.

**Comment by keiranmraine** [comment]
See https://github.com/bwa-mem2/bwa-mem2/issues/73

**Comment by Poshi** [comment]
Oh! Thanks! I only checked the open issues. O assumed all the closed ones would had been already solved.
