### ISSUE TITLE
intermittent failures: Shringking not supported yet

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [bwa-mem2/bwa-mem2#88]
I'm trying to use bwa-mem2 in a clinical variant calling pipeline, but I get intermittent errors when using bwa-mem2. The pipeline has a test suite, and when using bwa-mem2, some of the tests will randomly fail with the error message pasted below, though never the same tests twice.

The pipeline including the test data can be found here: https://github.com/LUMC/hutspot/tree/speedup
```
-----------------------------
Executing in AVX2 mode!!
-----------------------------
* Ref file: tests/data/reference/ref.fa
* Entering FMI_search
* Index file found. Loading index from tests/data/reference/ref.fa.bwt.8bit.32
* Reference seq len for bi-index = 33139
* Count:
0,      1
1,      9219
2,      16570
3,      23921
4,      33139

* Reading other elements of the index from files tests/data/reference/ref.fa
* Index prefix: tests/data/reference/ref.fa
* Read 0 ALT contigs
* Done reading Index!!
* Reading reference genome..
* Binary seq file = tests/data/reference/ref.fa.0123
* Reference genome size: 33138 bp
* Done reading reference genome !!

------------------------------------------
1. Memory pre-allocation for Chaining: 1114.7223 MB
2. Memory pre-allocation for BSW: 1916.9362 MB
3. Memory pre-allocation for BWT: 618.5134 MB
------------------------------------------
* Threads used (compute): 8
* No. of pipeline threads: 2

[0000] read_chunk: 80000000, work_chunk_size: 2274413, nseq: 15440
        [0000][ M::kt_pipeline] read 15440 sequences (2274413 bp)...
[0000] Calling mem_process_seqs.., task: 0
[0000] 1. Calling kt_for - worker_bwt
[0000] read_chunk: 80000000, work_chunk_size: 0, nseq: 0
[0009] Re-allocating SMEM data structures due to enc_qdb
Shringking not supported yet.
```

**Comment by Redmar-van-den-Berg** [comment]
It looks like these errors do not occur when I run the pytest-workflow tests one by one, instead of multiple tests concurrently. I'm not sure how this is possible, all tests are run independently and only share the same singularity image which contains bwa-mem2 and samtools-1.10. All input and reference files are copied to the test folder for the invocation of each test.

**Comment by yuk12** [comment]
Is the error reproducible (does it crashes same when run multiple time) ?
I am unable to access the link, looks like not public.

**Comment by Redmar-van-den-Berg** [comment]
If I run the tests multiple times (in parallel), some tests will always fail on the alignment step, though the specific input and reference files it crashes on are different every time.

I've ruled out that the tasks are running out of memory, since the same issue occurs on a system with 16GB and 100GB of RAM. Could there be some shared memory issue when multiple instances of bwa-mem2 are running at the same time?

The public version of the pipeline is here: https://github.com/LUMC/hutspot/tree/speedup

**Comment by Redmar-van-den-Berg** [comment]
I did some more testing trying to reproduce this error outside of the pipeline, and I have found the following:

1. No matter how many processes you start using the same reference and inputs, it does not crash when using only a single thread (tested with up to 67 processes running at the same time)
2. However, when you give each bwa-mem2 process 8 threads, I can reliably get crashes when running 10 processes at the same time. 

Here is the script I used to run the tests, using the test data from the pipeline linked above
```bash
#!/usr/bin/env bash

set -euo pipefail

fork=$1

BWA_MEM2="./bwa-mem2-2.0_x64-linux/bwa-mem2 mem"
REF="hutspot/tests/data/reference/ref.fa"
FORWARD="hutspot/tests/data/fastq/micro_R1.fq.gz"
REVERSE="hutspot/tests/data/fastq/micro_R2.fq.gz"
THREADS=8

rm -f bwa_mem*
for i in `seq ${fork}`; do
    set -eo pipefail ;${BWA_MEM2} \
        -t ${THREADS} ${REF} ${FORWARD} ${REVERSE} \
        2> bwa_mem2_log_${i}.log | wc -l > bwa_mem_${i}_lines.txt&
done

wait
echo DONE
```
Running the script, you might need to run it several times to trigger the bug
```bash
./run.sh 10
./run.sh: line 20: 442770 Aborted                 (core dumped) ${BWA_MEM2} -t ${THREADS} ${REF} ${FORWARD} ${REVERSE} 2> bwa_mem2_log_${i}.log
     442771 Done                    | wc -l > bwa_mem_${i}_lines.txt
./run.sh: line 20: 442772 Aborted                 (core dumped) ${BWA_MEM2} -t ${THREADS} ${REF} ${FORWARD} ${REVERSE} 2> bwa_mem2_log_${i}.log
     442773 Done                    | wc -l > bwa_mem_${i}_lines.txt
./run.sh: line 20: 442774 Segmentation fault      (core dumped) ${BWA_MEM2} -t ${THREADS} ${REF} ${FORWARD} ${REVERSE} 2> bwa_mem2_log_${i}.log
     442775 Done                    | wc -l > bwa_mem_${i}_lines.txt
```
Example of the errors I get:
```
-----------------------------
Executing in AVX2 mode!!
-----------------------------
* Ref file: hutspot/tests/data/reference/ref.fa
* Entering FMI_search
* Index file found. Loading index from hutspot/tests/data/reference/ref.fa.bwt.8bit.32
* Reference seq len for bi-index = 33139
* Count:
0,  1
1,  9219
2,  16570
3,  23921
4,  33139

* Reading other elements of the index from files hutspot/tests/data/reference/ref.fa
* Index prefix: hutspot/tests/data/reference/ref.fa
* Read 0 ALT contigs
* Done reading Index!!
* Reading reference genome..
* Binary seq file = hutspot/tests/data/reference/ref.fa.0123
* Reference genome size: 33138 bp
* Done reading reference genome !!

------------------------------------------
1. Memory pre-allocation for Chaining: 1114.7223 MB
2. Memory pre-allocation for BSW: 1916.9362 MB
3. Memory pre-allocation for BWT: 618.5134 MB
------------------------------------------
* Threads used (compute): 8
* No. of pipeline threads: 2

[0000] read_chunk: 80000000, work_chunk_size: 2276743, nseq: 15440
    [0000][ M::kt_pipeline] read 15440 sequences (2276743 bp)...
[0000] read_chunk: 80000000, work_chunk_size: 0, nseq: 0
[0000] Calling mem_process_seqs.., task: 0
[0000] 1. Calling kt_for - worker_bwt
[0010] Re-allocating SMEM data structures due to enc_qdb
malloc(): corrupted top size
```

**Comment by yuk12** [comment]
Looks like a memory corruption.
Does it fail with 1 process using 8 threads? or the crash only happens when multiple bwa-mem2 processes are running?

**Comment by Redmar-van-den-Berg** [comment]
It only ever fails with multiple bwa-mem2 processes are running on the same system.

**Comment by rhpvorderman** [comment]
This does make it not usable in a HPC environment such as when using a slurm scheduler, as multiple bwa-mem2 jobs can not be scheduled on the same node.

**Comment by keiranmraine** [comment]
Have you tried using the latest release ([2.1, 15th October 2020](https://github.com/bwa-mem2/bwa-mem2/releases/tag/v2.1))?

**Comment by Redmar-van-den-Berg** [comment]
It looks like I am no longer able to trigger this bug on my system, even when starting 400 concurrent processes using 8 threads (on a very small test data set).

I will try to get some larger test files so bwa can run longer, and do a second test.

```bash
BWA_MEM2="./bwa-mem2-2.1_x64-linux/bwa-mem2 mem"
redmar@ryzen-5-3600:~/bwa-mem2$ ./run.sh 1
DONE
redmar@ryzen-5-3600:~/bwa-mem2$ ./run.sh 10
DONE
redmar@ryzen-5-3600:~/bwa-mem2$ ./run.sh 100
DONE
redmar@ryzen-5-3600:~/bwa-mem2$ ./run.sh 200
DONE
redmar@ryzen-5-3600:~/bwa-mem2$ ./run.sh 200
DONE
redmar@ryzen-5-3600:~/bwa-mem2$ ./run.sh 200
DONE
redmar@ryzen-5-3600:~/bwa-mem2$ ./run.sh 200
DONE
redmar@ryzen-5-3600:~/bwa-mem2$ ./run.sh 200
DONE
redmar@ryzen-5-3600:~/bwa-mem2$ ./run.sh 200
DONE
redmar@ryzen-5-3600:~/bwa-mem2$ ./run.sh 200
DONE
redmar@ryzen-5-3600:~/bwa-mem2$ ./run.sh 400
DONE
redmar@ryzen-5-3600:~/bwa-mem2$ ./run.sh 400
DONE
redmar@ryzen-5-3600:~/bwa-mem2$ ./run.sh 400
DONE
redmar@ryzen-5-3600:~/bwa-mem2$ ./run.sh 400
DONE
redmar@ryzen-5-3600:~/bwa-mem2$ ./run.sh 400
DONE
redmar@ryzen-5-3600:~/bwa-mem2$ ./run.sh 400
DONE
redmar@ryzen-5-3600:~/bwa-mem2$ ./run.sh 400
DONE
redmar@ryzen-5-3600:~/bwa-mem2$ ./run.sh 400
DONE
redmar@ryzen-5-3600:~/bwa-mem2$ ./run.sh 400
DONE
```

**Comment by Redmar-van-den-Berg** [comment]
I still get the same error with a bigger dataset running BWA2.1
```bash
BWA_MEM2="./bwa-mem2-2.1_x64-linux/bwa-mem2 mem"
REF="bwa-mem2-ref/ref.fa"
$ ./run_GIAB.sh 2                                                                          
                                                                                                                           
./run_GIAB.sh: line 27:  8660 Segmentation fault      (core dumped) ${BWA_MEM2} -t ${THREADS} ${REF} ${FORWARD} ${REVERSE} 
2> bwa_mem2_log_${i}.log                                                                                                   
      8661 Done                    | wc -l > bwa_mem_${i}_lines.txt                                                        
DONE                                                                   
```

**Comment by Redmar-van-den-Berg** [comment]
For what it is worth, I get the same error when I use the bwa-mem2 version 2.1 from Conda

**Comment by yuk12** [comment]
I am looking into it. will get back to you soon.

**Comment by yuk12** [comment]
Please try with the latest commit. Also, make sure that you are not running out of memory when running multiple processes. I could not reproduce the issue on the latest commit. If the issue still persists then please share the data to reproduce the issue.

**Comment by Redmar-van-den-Berg** [comment]
Hi,

I've tried to replicate the issue with the compiled version of the latest commit (v2.1-4-gebc2378), and I can no longer get bwa-mem2 to crash.

To double check, I also compiled the version 2.1 release and ran my test, and the locally compiled version 2.1 crashes. So it looks like the last commit did resolve this issue, thanks!
