### ISSUE TITLE
Wheat 17G genome build index Segmentation fault

### ISSUE THREAD

**Issue by fei0810** [bwa-mem2/bwa-mem2#9]
Hi
I want to use bwa-mem2 in wheat genome (17G) .
bwa-mem2 was compiled from source, but the program had an segmentation fault when building index.

```sh
bwa-mem2 index -p CS_parts_bwamem2 161010_Chinese_Spring_v1.0_pseudomolecules_parts.fasta

[bwa_index] Pack FASTA... 85.80 sec
init ticks = 763897684114
ref seq len = 29094523130
binary seq ticks = 497034160160
build index ticks = 21694227971367
ref_seq_len = 29094523130
count = 0, 7837288578, 14547261565, 21257234552, 29094523130
BWT[12766107114] = 4
CP_SHIFT = 5, CP_MASK = 31
sizeof CP_OCC = 64
Segmentation fault
```

When segementation fault, I got 5 output files:

```sh
  28G CS_parts_bwamem2.0123
  12M CS_parts_bwamem2.amb
 2.1K CS_parts_bwamem2.ann
  55G CS_parts_bwamem2.bwt.8bit.32
 3.4G CS_parts_bwamem2.pac
```

My system info : Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux ; **512G memory**

By the way, bwa-mem works well. The genome file : ftp://ftp.ensemblgenomes.org/pub/plants/release-43/fasta/triticum_aestivum/dna/

**Comment by sanchit-misra** [comment]
We will look into this and get back to you.

**Comment by fei0810** [comment]
> We will look into this and get back to you.

Hi, is there any progress on this issue?

**Comment by sanchit-misra** [comment]
We are working on it. We have reproduced the bug. Trying to fix it now.

**Comment by sanchit-misra** [comment]
Most likely, you are running out of memory. Creating the index using the current code needs maximum memory of 34N Bytes, where N is the size of the reference sequence. With the wheat genome, it would be 34*17 = 578 GB. We are trying to reduce the maximum memory required.

**Comment by Dagsbio** [comment]
Hi, I'm getting same error when indexing hg19.fa with 32GB RAM:

bwa-mem2 index hg19.fa 
[bwa_index] Pack FASTA... 7.61 sec
init ticks = 257657731164
ref seq len = 6274322528
binary seq ticks = 133066087488
Segmentation fault (core dumped)

**Comment by sanchit-misra** [comment]
Hi, that is because the indexing of human genome requires nearly 40 GB of memory.

**Comment by sanchit-misra** [comment]
@fei0810 Fixed the code to work with wheat genome. Now, it needs 28N space = 28*17 = 476 GB to build wheat genome.
Also, fixed the rest of the code so that wheat genome (and other larger genomes) can be mapped to correctly.

**Comment by fei0810** [comment]
> @fei0810 Fixed the code to work with wheat genome. Now, it needs 28N space = 28*17 = 476 GB to build wheat genome.
> Also, fixed the rest of the code so that wheat genome (and other larger genomes) can be mapped to correctly.

Coooool! 
Thank you so much.
