### ISSUE TITLE
[request] could you recompile and release bwm-mem2?

### ISSUE THREAD

**Issue by dauss75** [bwa-mem2/bwa-mem2#92]
I am getting this error and have found the fix was updated after the current release.
bwa-mem2: src/profiling.cpp:163: int display_stats(int): Assertion `agg2 != 0' failed

I'd very much appreciated if you could redistribute the binary version of bwa-mem2.

Thanks,
Segun

**Comment by yuk12** [comment]
Soon we will make a release. Just wanted to point out that this error does not affect the output or the performance.

**Comment by dauss75** [comment]
Thank you and agreed on your note.  Wanted to have the bwa-mem2 in our pipeline and worked fine aligning reads to the human reference genome, but when checking sample contamination by aligning to viral genomes it failed due to no reads aligned.

**Comment by sanchit-misra** [comment]
We have made a new release with the new set of pre-compiled binaries.
