### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by ana-stankovic** [bwa-mem2/bwa-mem2#95]
Hello, when is a new release planned that includes all the changes implemented concerning the Index?
We are interested in including the bwa-mem2 into our pipelines and since we saw these changes we are not sure which version to include.

**Comment by sanchit-misra** [comment]
We are trying to do the next release with reduced index size by the end of this month.

**Comment by sanchit-misra** [comment]
Hi @ana-stankovic, the current master branch has all our changes to reduce the index. We should release the binaries soon but you should be able to use the latest commit: f0d047b.

**Comment by sanchit-misra** [comment]
We have made a new release with the new set of pre-compiled binaries.
