### ISSUE TITLE
unable to build from source

### ISSUE THREAD

**Issue by cmeesters** [bwa-mem2/bwa-mem2#96]
Hi,

when building from source, I get the error that `safe_mem_lib.h` is missing - regardless of the used compiler. (Aim is to provide bwa-mem2 to the easybuild community.)

I suppose this is libsafec, which is missing? If so, which implementation have you been using? If not, which library does provide the missing header? (Or is there a way around the requirement?)

Best regards,
Christian Meesters

**Comment by yuk12** [comment]
You need to fetch the safestringlib submodule as well before compiling. Please follow the instructions from readme.

**Comment by cmeesters** [comment]
Sorry for the late reply (I was terribly busy) and thank you for the info.

In essence: My fault to overlook this. However, I was referring to the tarballed source. This does not mention this dependency (other then in the code). In order to include your software in our build framework (and hence to a significant part of the HPC community) a modulefile for safestringlib (resp. an easyconfig-file to install this) can be created, too. It would be a nice gesture to reflect this dependency in the source download of new releases, too. 

'git clone ...' does not provide a reliable reference to otherwise versioned software and is hence not an alternative. Also, some cluster administrators do not allow uncontrolled git access (regardless of the provider) by users anymore, due to security considerations. Hence, providing software in modulefiles (which is always release based) is paramount to provide service to users.

I hope this make sense to you.

**Comment by keiranmraine** [comment]
This is possible via clone, the `--branch` option supports tags:

```
git clone --depth 1 --branch v2.0 --recursive git@github.com:bwa-mem2/bwa-mem2.git
```
