### ISSUE TITLE
Process teminates with "Illegal Instruction"

### ISSUE THREAD

**Issue by 7PintsOfCherryGarcia** [bwa-mem2/bwa-mem2#97]
bwa-mem2 compiled from source with "make"

system:
    Red Hat 4.8.5-39
    gcc (GCC) 4.8.5 20150623
    GNU Make 3.82
lscpu:
    Architecture:          x86_64
    CPU op-mode(s):        32-bit, 64-bit
    Byte Order:            Little Endian
    CPU(s):                88
    On-line CPU(s) list:   0-87
    Thread(s) per core:    2
    Core(s) per socket:    22
    Socket(s):             2
    NUMA node(s):          2
   Vendor ID:             GenuineIntel
    CPU family:            6
    Model:                 79
    Model name:            Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz
    Stepping:              1
    CPU MHz:               2799.951
    CPU max MHz:           3600.0000
    CPU min MHz:           1200.0000
    BogoMIPS:              4400.04
    Virtualization:        VT-x

bwa-mem2 stderr log WITH valgrind error report:

[bwaerr_valgrind.txt](https://github.com/bwa-mem2/bwa-mem2/files/5260612/bwaerr_valgrind.txt)

**Comment by yuk12** [comment]
Do you face the same issue with the binaries also?

**Comment by 7PintsOfCherryGarcia** [comment]
bwa-mem2: Exits immediately with "ERROR: fail to find the right executable"

bwa-mem2.avx2: Exists immediately with "Illegal instruction (core dumped)"  [bwa-mem2.avx2.txt](https://github.com/bwa-mem2/bwa-mem2/files/5292129/bwa-mem2.avx2.txt)

bwa-mem2.avx512bw: Exits, instructions not supported by CPU or OS

bwa-mem2.sse41: Exits with "Illegal instruction (core dumped)"  [bwa-mem2.sse41.txt](https://github.com/bwa-mem2/bwa-mem2/files/5292155/bwa-mem2.sse41.txt)

All versions except bwa-mem2 and bwa-mem2.avx512bw build index correctly.

**Comment by yuk12** [comment]
bwa-mem2.avx512bw won't execute because your processor does not support avx512bw. But, It should execute the avx2 and sse.
I am assuming without valgrid also it reports the same error for avx2 and sse?  I tried avx2 and sse on a slightly older machine than yours (
E5-2699V3) and it works properly.

**Comment by 7PintsOfCherryGarcia** [comment]
Well, the time invested in trying to make this work is no longer worth the time I would have saved compared to bwa so I won't keep digging for now.
