### ISSUE TITLE
Does not compile on ARM

### ISSUE THREAD

**Issue by mp-consulting** [bwa-mem2/bwa-mem2#98]
Attempting to run `make` on an ARM system yields the following error:

```
g++: error: unrecognized command line option '-msse4.1'
make: *** [Makefile:81: src/fastmap.o] Error 1
```

**Comment by mp15** [comment]
The solution to this specific error is to create a new Makefile target that removes `-msse4.1` from that target. That only scratches the surface though, to get a proper speedup you need to use one of the portability libraries that translates AVX2/SSE intrinsics to Neon intrinsics. However, as this is a rival platform I suspect doing this might be out of scope for Intel developers, thus you may need to contribute/hire some developers time to do this.

**Comment by sanchit-misra** [comment]
Agree with @mp15

**Comment by 0820LL** [comment]
Is there a solution to compile bwa-mem2 on ARM？
